from __future__ import annotations

import json
import re
import subprocess
import unittest
from pathlib import Path
from urllib.parse import urlsplit
from xml.etree import ElementTree


ROOT = Path(__file__).resolve().parents[2]
BUILDER = ROOT / "scripts/build_public_docs.py"
SOURCE_ROOT = ROOT / "docs/wiki"
PUBLIC_ROOT = ROOT / "docs/public_overview"
DOCS_ROOT = PUBLIC_ROOT / "docs"
WORKFLOW = ROOT / ".github/workflows/public-docs.yml"
SOURCE_FILES = (
    "README.md",
    "getting-started.md",
    "concepts.md",
    "cli.md",
    "integrations.md",
    "operations.md",
    "troubleshooting.md",
    "releases.md",
)
ROUTES = (
    "/docs/",
    "/docs/getting-started/",
    "/docs/concepts/",
    "/docs/cli/",
    "/docs/integrations/",
    "/docs/operations/",
    "/docs/troubleshooting/",
    "/docs/releases/",
)


class PublicDocsTests(unittest.TestCase):
    def test_generated_documentation_is_current(self) -> None:
        result = subprocess.run(
            ["python3", str(BUILDER), "--check"],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        payload = json.loads(result.stdout)
        self.assertTrue(payload["ok"])
        self.assertEqual(payload["drift"], [])
        self.assertEqual(len(payload["sources"]), len(SOURCE_FILES))
        self.assertEqual(len(payload["managedOutputs"]), len(SOURCE_FILES) + 1)

    def test_sources_map_one_to_one_to_stable_routes(self) -> None:
        for filename, route in zip(SOURCE_FILES, ROUTES, strict=True):
            with self.subTest(source=filename):
                source = SOURCE_ROOT / filename
                output = DOCS_ROOT / (
                    "index.html" if route == "/docs/" else f"{route.removeprefix('/docs/').strip('/')}/index.html"
                )
                self.assertTrue(source.is_file())
                self.assertTrue(output.is_file())
                page = output.read_text(encoding="utf-8")
                self.assertEqual(len(re.findall(r"<h1(?:\s|>)", page)), 1)
                self.assertIn(
                    f'<link rel="canonical" href="https://contextlattice.io{route}"',
                    page,
                )
                self.assertIn(f'content="docs/wiki/{filename}"', page)
                self.assertIn(
                    f"https://github.com/sheawinkler/ContextLattice/blob/main/docs/wiki/{filename}",
                    page,
                )
                self.assertIn('href="/docs/docs.css?v=20260724b"', page)
                self.assertIn("Generated by scripts/build_public_docs.py", page)
                primary_nav = re.search(
                    r'<nav class="site-nav" aria-label="Primary">(.*?)</nav>',
                    page,
                    re.DOTALL,
                )
                self.assertIsNotNone(primary_nav)
                self.assertEqual(len(re.findall(r"<a\s", primary_nav.group(1))), 5)
                self.assertNotRegex(page, r"/(?:Users|Volumes)/")

    def test_search_index_covers_every_source_without_html_injection(self) -> None:
        index = json.loads((DOCS_ROOT / "search-index.json").read_text(encoding="utf-8"))
        self.assertEqual(index["schemaId"], "contextlattice_public_docs_search.v1")
        self.assertEqual(
            [document["href"] for document in index["documents"]],
            list(ROUTES),
        )
        for document in index["documents"]:
            self.assertTrue(document["title"])
            self.assertTrue(document["summary"])
            self.assertTrue(document["headings"])
            self.assertGreater(len(document["text"]), 80)
        search_script = (DOCS_ROOT / "docs.js").read_text(encoding="utf-8")
        self.assertIn('fetch("/docs/search-index.json")', search_script)
        self.assertIn("textContent", search_script)
        self.assertNotIn("innerHTML", search_script)

    def test_sitemap_covers_docs_and_wiki_remains_compatibility_alias(self) -> None:
        sitemap = ElementTree.fromstring(
            (PUBLIC_ROOT / "sitemap.xml").read_text(encoding="utf-8")
        )
        paths = {
            urlsplit((element.text or "").strip()).path
            for element in sitemap.iter()
            if element.tag.rsplit("}", 1)[-1] == "loc"
        }
        self.assertTrue(set(ROUTES) <= paths)
        self.assertIn("/wiki.html", paths)

        wiki = (PUBLIC_ROOT / "wiki.html").read_text(encoding="utf-8")
        self.assertIn('http-equiv="refresh" content="0; url=docs/"', wiki)
        self.assertIn('rel="canonical" href="https://contextlattice.io/docs/"', wiki)
        self.assertEqual(len(re.findall(r"<h1(?:\s|>)", wiki)), 1)

    def test_release_sync_copies_recursive_docs_directory(self) -> None:
        sync = (ROOT / "scripts/sync_public_overview.sh").read_text(encoding="utf-8")
        self.assertIn('if [[ -d "$PUBLIC_SOURCE_DIR/docs" ]]; then', sync)
        self.assertIn('cp -R "$PUBLIC_SOURCE_DIR/docs" "$PUBLIC_DIR/docs"', sync)

    def test_documentation_assets_keep_editorial_contract(self) -> None:
        css = (DOCS_ROOT / "docs.css").read_text(encoding="utf-8")
        self.assertIn("--docs-sidebar", css)
        self.assertIn("var(--cl-accent)", css)
        self.assertIn("border: 1px solid var(--cl-line)", css)
        self.assertIn("overflow-wrap: normal", css)
        self.assertIn("text-wrap: balance", css)
        self.assertIn("@media (max-width: 980px)", css)
        self.assertIn("@media (max-width: 760px)", css)
        self.assertIn("@media (prefers-reduced-motion: reduce)", css)
        for route in ROUTES:
            page_path = DOCS_ROOT / (
                "index.html" if route == "/docs/" else f"{route.removeprefix('/docs/').strip('/')}/index.html"
            )
            page = page_path.read_text(encoding="utf-8")
            self.assertIn("<strong>Continuity Fieldbook</strong>", page)
            self.assertIn('placeholder="Search the continuity fieldbook"', page)
            self.assertNotIn("<strong>Field Manual</strong>", page)

    def test_homepage_restores_the_full_bounded_lattice_field(self) -> None:
        page = (PUBLIC_ROOT / "index.html").read_text(encoding="utf-8")
        editorial_css = (PUBLIC_ROOT / "styles-editorial.css").read_text(encoding="utf-8")
        hero_css = (PUBLIC_ROOT / "styles-hero-lattice.css").read_text(encoding="utf-8")

        self.assertIn('class="signal-lattice hero-art"', page)
        self.assertEqual(page.count('class="hero-lattice"'), 1)
        self.assertGreaterEqual(page.count('class="hl-lane '), 10)
        self.assertNotIn('class="signal-line ', page)
        self.assertIn("aspect-ratio: 340 / 210", editorial_css)
        self.assertIn("contain: layout paint", hero_css)
        self.assertIn("@media (prefers-reduced-motion: reduce)", hero_css)
        self.assertNotIn("hl-lane-flow-haze", page)

    def test_updates_are_a_direct_itemized_release_ledger(self) -> None:
        page = (PUBLIC_ROOT / "updates.html").read_text(encoding="utf-8")
        cards = re.findall(
            r'<article class="update-card">(.*?)</article>',
            page,
            re.DOTALL,
        )
        self.assertGreaterEqual(len(cards), 60)
        self.assertNotRegex(page, r"<ul>\s*<ul>")
        for index, card in enumerate(cards, start=1):
            with self.subTest(card=index):
                self.assertNotRegex(card, r"<p(?:\s|>)")
                items = re.findall(r"<li(?:\s[^>]*)?>(.*?)</li>", card, re.DOTALL)
                self.assertGreaterEqual(len(items), 1)
                for item in items:
                    plain = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", item)).strip()
                    self.assertLessEqual(len(plain), 260)

    def test_public_background_is_static_fabric_not_an_animated_grid(self) -> None:
        fabric = (PUBLIC_ROOT / "assets/lattice-fabric.svg").read_text(encoding="utf-8")
        for stylesheet in ("styles-editorial.css", "styles-gray.css", "styles-fracture.css"):
            css = (PUBLIC_ROOT / stylesheet).read_text(encoding="utf-8")
            self.assertIn('url("assets/lattice-fabric.svg")', css)
        self.assertGreaterEqual(fabric.count("<path"), 18)
        self.assertNotIn("<animate", fabric)

    def test_public_docs_workflow_covers_sources_outputs_and_drift_gates(self) -> None:
        workflow = WORKFLOW.read_text(encoding="utf-8")
        for path in (
            "docs/public_overview/**",
            "docs/wiki/**",
            "scripts/build_public_docs.py",
            "scripts/tests/test_public_docs.py",
            ".github/workflows/public-docs.yml",
        ):
            self.assertGreaterEqual(workflow.count(f'- "{path}"'), 2, path)
        self.assertIn("python3 scripts/build_public_docs.py --check", workflow)
        self.assertIn(
            "python3 -m unittest scripts.tests.test_public_docs scripts.tests.test_public_product_truth",
            workflow,
        )
        self.assertIn(
            "scripts/agent/audit-public-product-truth --lane public --pretty",
            workflow,
        )

    def test_visual_audit_covers_every_public_route_and_heading_integrity(self) -> None:
        sitemap = ElementTree.fromstring(
            (PUBLIC_ROOT / "sitemap.xml").read_text(encoding="utf-8")
        )
        paths = {
            urlsplit((element.text or "").strip()).path
            for element in sitemap.iter()
            if element.tag.rsplit("}", 1)[-1] == "loc"
        }
        visual_audit = (
            ROOT / "contextlattice-dashboard/scripts/audit_public_site_experience.mjs"
        ).read_text(encoding="utf-8")

        for path in sorted(paths):
            with self.subTest(path=path):
                self.assertIn(f'"{path}"', visual_audit)
        self.assertIn('{ name: "compact-desktop", width: 1024, height: 900 }', visual_audit)
        self.assertIn("headingMidWordBreaks", visual_audit)
        self.assertIn("failedResources", visual_audit)
        self.assertIn("homeHeroAspectRatio", visual_audit)
        self.assertIn("updatesDirectSummaryCount", visual_audit)

    def test_every_public_html_route_declares_the_site_icon(self) -> None:
        sitemap = ElementTree.fromstring(
            (PUBLIC_ROOT / "sitemap.xml").read_text(encoding="utf-8")
        )
        paths = {
            urlsplit((element.text or "").strip()).path
            for element in sitemap.iter()
            if element.tag.rsplit("}", 1)[-1] == "loc"
        }
        for route in sorted(paths):
            with self.subTest(route=route):
                if route == "/":
                    page_path = PUBLIC_ROOT / "index.html"
                elif route.endswith(".html"):
                    page_path = PUBLIC_ROOT / route.removeprefix("/")
                else:
                    page_path = PUBLIC_ROOT / route.strip("/") / "index.html"
                page = page_path.read_text(encoding="utf-8")
                self.assertIn('rel="icon"', page)


if __name__ == "__main__":
    unittest.main()
