services:
  qdrant:
    image: qdrant/qdrant:v1.7.1
    restart: unless-stopped
    volumes: [ "qdrant_storage:/qdrant/storage" ]
    ports: [ "6333:6333" ]   # host access useful for local admin

  mcp-qdrant:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      QDRANT_URL: "${QDRANT_URL:-http://qdrant:6333}"
      QDRANT_COLLECTION: "${QDRANT_COLLECTION:-memmcp_notes}"
      EMBEDDING_MODEL: "${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}"
      FASTMCP_SERVER_HOST: 0.0.0.0
      FASTMCP_SERVER_PORT: 8002
    depends_on:
      qdrant: { condition: service_started }
    restart: unless-stopped
    # Internal only (mcp-proxy will call http://mcp-qdrant:8002/mcp)
    expose: [ "8002" ]

  mindsdb:
    image: mindsdb/mindsdb:22.11   # pin a conservative working tag
    environment:
      MINDSDB_APIS: "http,mysql"
    restart: unless-stopped
    # Internal; we don’t need to publish unless you want to hit it directly
    expose: [ "47334", "47337" ]

  mindsdb-http-proxy:
    build:
      context: .
      dockerfile: Dockerfile.mindsdb-http-proxy
    environment:
      MINDSDB_HTTP_URL: "http://mindsdb:47334"
    depends_on:
      mindsdb: { condition: service_started }
    restart: unless-stopped
    expose: [ "8004" ]

  mcp-proxy:
    image: ghcr.io/tbxark/mcp-proxy:v0.39.1
    command: ["/main","--config","/config/config.json"]
    volumes:
      - type: bind
        source: ./configs/mcp-proxy.config.json
        target: /config/config.json
        read_only: true
    ports: [ "9090:9090" ]
    depends_on:
      mcp-qdrant: { condition: service_started }
      mindsdb-http-proxy: { condition: service_started }
    restart: unless-stopped

volumes:
  qdrant_storage: {}
