// Code generated by scripts/agent/generate-agent-contract-types; DO NOT EDIT.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AgentContractRef {
    pub schema_id: &'static str,
    pub payload_kind: &'static str,
    pub contract_version: u32,
    pub required_output_mode: &'static str,
}

pub const AGENT_CONTRACT_REGISTRY_ID: &str = "contextlattice_agent_output_contracts";
pub const AGENT_CONTRACT_REGISTRY_VERSION: u32 = 17;

pub const A2A_READINESS_PROFILE_V1: &str = "a2a_readiness_profile.v1";
pub const AGENT_FLIGHT_RECORDER_EVENT_V1: &str = "agent_flight_recorder_event.v1";
pub const AGENT_PREFLIGHT_RESPONSE_V1: &str = "agent_preflight_response.v1";
pub const AGENT_PROMPT_CONTEXT_PACKAGE_V1: &str = "agent_prompt_context_package.v1";
pub const AGENT_RUN_TRACE_V1: &str = "agent_run_trace.v1";
pub const AGENT_SESSION_ROLLUP_V1: &str = "agent_session_rollup.v1";
pub const AGENT_SPAN_V1: &str = "agent_span.v1";
pub const AGENT_TASK_LEASE_V1: &str = "agent_task_lease.v1";
pub const AGENT_TASK_RESULT_V1: &str = "agent_task_result.v1";
pub const ANTI_SCHEMING_PROTOCOL_V1: &str = "anti_scheming_protocol.v1";
pub const CODEX_COMPACT_HOOK_STDOUT_V1: &str = "codex_compact_hook_stdout.v1";
pub const CONTEXT_OVERFLOW_RECOVERY_V1: &str = "context_overflow_recovery.v1";
pub const CONTEXT_PACK_RESPONSE_V1: &str = "context_pack_response.v1";
pub const CONTRACT_ACKNOWLEDGEMENT_V1: &str = "contract_acknowledgement.v1";
pub const DREAM_MODE_RESPONSE_V1: &str = "dream_mode_response.v1";
pub const OBJECTIVE_RUNTIME_STATE_V1: &str = "objective_runtime_state.v1";
pub const POLICY_CONTEXT_PACKAGE_V1: &str = "policy_context_package.v1";
pub const RETRIEVAL_PLAN_V1: &str = "retrieval_plan.v1";
pub const RETRIEVAL_PROGRESS_V1: &str = "retrieval_progress.v1";
pub const REVIEW_MODE_RESPONSE_V1: &str = "review_mode_response.v1";
pub const RUN_ADVISOR_V1: &str = "run_advisor.v1";
pub const RUNNER_CAPABILITY_V1: &str = "runner_capability.v1";
pub const RUNNER_QUALITY_SAMPLE_V1: &str = "runner_quality_sample.v1";
pub const RUNNER_RESULT_V1: &str = "runner_result.v1";
pub const STEERING_COMMENT_V1: &str = "steering_comment.v1";
pub const SYNTHESIS_PACK_V1: &str = "synthesis_pack.v1";
pub const SYNTHESIS_PACK_V2: &str = "synthesis_pack.v2";
pub const TEMPORAL_CLAIM_V1: &str = "temporal_claim.v1";
pub const TEMPORAL_CLAIM_QUERY_V1: &str = "temporal_claim_query.v1";
pub const UNIVERSAL_AGENT_ADAPTER_RESPONSE_V1: &str = "universal_agent_adapter_response.v1";
pub const WRITEBACK_RESULT_V1: &str = "writeback_result.v1";

pub const AGENT_CONTRACT_IDS: &[&str] = &[
    A2A_READINESS_PROFILE_V1,
    AGENT_FLIGHT_RECORDER_EVENT_V1,
    AGENT_PREFLIGHT_RESPONSE_V1,
    AGENT_PROMPT_CONTEXT_PACKAGE_V1,
    AGENT_RUN_TRACE_V1,
    AGENT_SESSION_ROLLUP_V1,
    AGENT_SPAN_V1,
    AGENT_TASK_LEASE_V1,
    AGENT_TASK_RESULT_V1,
    ANTI_SCHEMING_PROTOCOL_V1,
    CODEX_COMPACT_HOOK_STDOUT_V1,
    CONTEXT_OVERFLOW_RECOVERY_V1,
    CONTEXT_PACK_RESPONSE_V1,
    CONTRACT_ACKNOWLEDGEMENT_V1,
    DREAM_MODE_RESPONSE_V1,
    OBJECTIVE_RUNTIME_STATE_V1,
    POLICY_CONTEXT_PACKAGE_V1,
    RETRIEVAL_PLAN_V1,
    RETRIEVAL_PROGRESS_V1,
    REVIEW_MODE_RESPONSE_V1,
    RUN_ADVISOR_V1,
    RUNNER_CAPABILITY_V1,
    RUNNER_QUALITY_SAMPLE_V1,
    RUNNER_RESULT_V1,
    STEERING_COMMENT_V1,
    SYNTHESIS_PACK_V1,
    SYNTHESIS_PACK_V2,
    TEMPORAL_CLAIM_V1,
    TEMPORAL_CLAIM_QUERY_V1,
    UNIVERSAL_AGENT_ADAPTER_RESPONSE_V1,
    WRITEBACK_RESULT_V1,
];

pub const AGENT_CONTRACTS: &[AgentContractRef] = &[
    AgentContractRef {
        schema_id: A2A_READINESS_PROFILE_V1,
        payload_kind: "a2a_readiness_profile",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_FLIGHT_RECORDER_EVENT_V1,
        payload_kind: "agent_flight_recorder_event",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_PREFLIGHT_RESPONSE_V1,
        payload_kind: "agent_preflight_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_PROMPT_CONTEXT_PACKAGE_V1,
        payload_kind: "agent_prompt_context_package",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_RUN_TRACE_V1,
        payload_kind: "agent_run_trace",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_SESSION_ROLLUP_V1,
        payload_kind: "agent_session_rollup",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_SPAN_V1,
        payload_kind: "agent_span",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_TASK_LEASE_V1,
        payload_kind: "agent_task_lease",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_TASK_RESULT_V1,
        payload_kind: "agent_task_result",
        contract_version: 1,
        required_output_mode: "json_object_or_markdown_with_json_frontmatter",
    },
    AgentContractRef {
        schema_id: ANTI_SCHEMING_PROTOCOL_V1,
        payload_kind: "policy_fragment",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CODEX_COMPACT_HOOK_STDOUT_V1,
        payload_kind: "codex_compact_hook_stdout",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_OVERFLOW_RECOVERY_V1,
        payload_kind: "context_overflow_recovery",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_PACK_RESPONSE_V1,
        payload_kind: "context_pack_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTRACT_ACKNOWLEDGEMENT_V1,
        payload_kind: "contract_acknowledgement",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: DREAM_MODE_RESPONSE_V1,
        payload_kind: "dream_mode_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: OBJECTIVE_RUNTIME_STATE_V1,
        payload_kind: "objective_runtime_state",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: POLICY_CONTEXT_PACKAGE_V1,
        payload_kind: "agent_policy_context_package",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RETRIEVAL_PLAN_V1,
        payload_kind: "adaptive_retrieval_plan",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RETRIEVAL_PROGRESS_V1,
        payload_kind: "retrieval_progress",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: REVIEW_MODE_RESPONSE_V1,
        payload_kind: "review_mode_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RUN_ADVISOR_V1,
        payload_kind: "run_advisor",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RUNNER_CAPABILITY_V1,
        payload_kind: "runner_capability",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RUNNER_QUALITY_SAMPLE_V1,
        payload_kind: "runner_quality_sample",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RUNNER_RESULT_V1,
        payload_kind: "runner_result",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: STEERING_COMMENT_V1,
        payload_kind: "steering_comment",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SYNTHESIS_PACK_V1,
        payload_kind: "synthesis_pack",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SYNTHESIS_PACK_V2,
        payload_kind: "proof_carrying_synthesis_pack",
        contract_version: 2,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: TEMPORAL_CLAIM_V1,
        payload_kind: "temporal_claim",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: TEMPORAL_CLAIM_QUERY_V1,
        payload_kind: "temporal_claim_query",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: UNIVERSAL_AGENT_ADAPTER_RESPONSE_V1,
        payload_kind: "universal_agent_adapter_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: WRITEBACK_RESULT_V1,
        payload_kind: "writeback_result",
        contract_version: 1,
        required_output_mode: "json_object",
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_contracts_are_present() {
        assert_eq!(
            AGENT_CONTRACT_REGISTRY_ID,
            "contextlattice_agent_output_contracts"
        );
        assert_eq!(AGENT_CONTRACT_IDS.len(), AGENT_CONTRACTS.len());
        assert!(AGENT_CONTRACT_IDS.contains(&POLICY_CONTEXT_PACKAGE_V1));
        assert!(AGENT_CONTRACT_IDS.contains(&A2A_READINESS_PROFILE_V1));
        assert!(AGENT_CONTRACT_IDS.contains(&CONTEXT_OVERFLOW_RECOVERY_V1));
    }
}
