// Code generated by scripts/agent/generate-agent-contract-types; DO NOT EDIT.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AgentContractRef {
    pub schema_id: &'static str,
    pub payload_kind: &'static str,
    pub contract_version: u32,
    pub required_output_mode: &'static str,
}

pub const AGENT_CONTRACT_REGISTRY_ID: &str = "contextlattice_agent_output_contracts";
pub const AGENT_CONTRACT_REGISTRY_VERSION: u32 = 1;

pub const A2A_READINESS_PROFILE_V1: &str = "a2a_readiness_profile.v1";
pub const AGENT_FLIGHT_RECORDER_EVENT_V1: &str = "agent_flight_recorder_event.v1";
pub const AGENT_PREFLIGHT_RESPONSE_V1: &str = "agent_preflight_response.v1";
pub const AGENT_SPAN_V1: &str = "agent_span.v1";
pub const AGENT_TASK_RESULT_V1: &str = "agent_task_result.v1";
pub const ANTI_SCHEMING_PROTOCOL_V1: &str = "anti_scheming_protocol.v1";
pub const CODEX_COMPACT_HOOK_STDOUT_V1: &str = "codex_compact_hook_stdout.v1";
pub const CONTEXT_PACK_RESPONSE_V1: &str = "context_pack_response.v1";
pub const CONTRACT_ACKNOWLEDGEMENT_V1: &str = "contract_acknowledgement.v1";
pub const POLICY_CONTEXT_PACKAGE_V1: &str = "policy_context_package.v1";
pub const WRITEBACK_RESULT_V1: &str = "writeback_result.v1";

pub const AGENT_CONTRACT_IDS: &[&str] = &[
    A2A_READINESS_PROFILE_V1,
    AGENT_FLIGHT_RECORDER_EVENT_V1,
    AGENT_PREFLIGHT_RESPONSE_V1,
    AGENT_SPAN_V1,
    AGENT_TASK_RESULT_V1,
    ANTI_SCHEMING_PROTOCOL_V1,
    CODEX_COMPACT_HOOK_STDOUT_V1,
    CONTEXT_PACK_RESPONSE_V1,
    CONTRACT_ACKNOWLEDGEMENT_V1,
    POLICY_CONTEXT_PACKAGE_V1,
    WRITEBACK_RESULT_V1,
];

pub const AGENT_CONTRACTS: &[AgentContractRef] = &[
    AgentContractRef {
        schema_id: A2A_READINESS_PROFILE_V1,
        payload_kind: "a2a_readiness_profile",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_FLIGHT_RECORDER_EVENT_V1,
        payload_kind: "agent_flight_recorder_event",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_PREFLIGHT_RESPONSE_V1,
        payload_kind: "agent_preflight_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_SPAN_V1,
        payload_kind: "agent_span",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_TASK_RESULT_V1,
        payload_kind: "agent_task_result",
        contract_version: 1,
        required_output_mode: "json_object_or_markdown_with_json_frontmatter",
    },
    AgentContractRef {
        schema_id: ANTI_SCHEMING_PROTOCOL_V1,
        payload_kind: "policy_fragment",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CODEX_COMPACT_HOOK_STDOUT_V1,
        payload_kind: "codex_compact_hook_stdout",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_PACK_RESPONSE_V1,
        payload_kind: "context_pack_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTRACT_ACKNOWLEDGEMENT_V1,
        payload_kind: "contract_acknowledgement",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: POLICY_CONTEXT_PACKAGE_V1,
        payload_kind: "agent_policy_context_package",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: WRITEBACK_RESULT_V1,
        payload_kind: "writeback_result",
        contract_version: 1,
        required_output_mode: "json_object",
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_contracts_are_present() {
        assert_eq!(
            AGENT_CONTRACT_REGISTRY_ID,
            "contextlattice_agent_output_contracts"
        );
        assert_eq!(AGENT_CONTRACT_IDS.len(), AGENT_CONTRACTS.len());
        assert!(AGENT_CONTRACT_IDS.contains(&POLICY_CONTEXT_PACKAGE_V1));
        assert!(AGENT_CONTRACT_IDS.contains(&A2A_READINESS_PROFILE_V1));
    }
}
