// Code generated by scripts/agent/generate-agent-contract-types; DO NOT EDIT.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AgentContractRef {
    pub schema_id: &'static str,
    pub payload_kind: &'static str,
    pub contract_version: u32,
    pub required_output_mode: &'static str,
}

pub const AGENT_CONTRACT_REGISTRY_ID: &str = "contextlattice_agent_output_contracts";
pub const AGENT_CONTRACT_REGISTRY_VERSION: u32 = 54;

pub const A2A_READINESS_PROFILE_V1: &str = "a2a_readiness_profile.v1";
pub const AGENT_CONTEXT_PROFILE_V1: &str = "agent_context_profile.v1";
pub const AGENT_FLIGHT_RECORDER_EVENT_V1: &str = "agent_flight_recorder_event.v1";
pub const AGENT_PACKET_V1: &str = "agent_packet.v1";
pub const AGENT_PACKET_DELTA_V1: &str = "agent_packet_delta.v1";
pub const AGENT_PACKET_RECONSTRUCTION_V1: &str = "agent_packet_reconstruction.v1";
pub const AGENT_PREFLIGHT_RESPONSE_V1: &str = "agent_preflight_response.v1";
pub const AGENT_PROMPT_CONTEXT_PACKAGE_V1: &str = "agent_prompt_context_package.v1";
pub const AGENT_PROOF_TIMELINE_V1: &str = "agent_proof_timeline.v1";
pub const AGENT_RUN_TRACE_V1: &str = "agent_run_trace.v1";
pub const AGENT_SESSION_ROLLUP_V1: &str = "agent_session_rollup.v1";
pub const AGENT_SPAN_V1: &str = "agent_span.v1";
pub const AGENT_TASK_LEASE_V1: &str = "agent_task_lease.v1";
pub const AGENT_TASK_RESULT_V1: &str = "agent_task_result.v1";
pub const AGGREGATE_CONTRIBUTION_V1: &str = "aggregate_contribution.v1";
pub const AGGREGATE_REPORT_V1: &str = "aggregate_report.v1";
pub const ANTI_SCHEMING_PROTOCOL_V1: &str = "anti_scheming_protocol.v1";
pub const ASYNC_STEERING_DELIVERY_V1: &str = "async_steering_delivery.v1";
pub const ASYNC_STEERING_EVENT_V1: &str = "async_steering_event.v1";
pub const ASYNC_STEERING_STREAM_ITEM_V1: &str = "async_steering_stream_item.v1";
pub const CAUSAL_BRIDGE_EXPLANATION_V1: &str = "causal_bridge_explanation.v1";
pub const CODEX_COMPACT_HOOK_STDOUT_V1: &str = "codex_compact_hook_stdout.v1";
pub const COLLABORATIVE_CONTEXT_GRANT_V1: &str = "collaborative_context_grant.v1";
pub const COLLABORATIVE_CONTEXT_GRANT_DECISION_V1: &str = "collaborative_context_grant_decision.v1";
pub const COLLABORATIVE_CONTEXT_GRANT_REVOCATION_V1: &str =
    "collaborative_context_grant_revocation.v1";
pub const CONTEXT_CONTINUATION_ENVELOPE_V1: &str = "context_continuation_envelope.v1";
pub const CONTEXT_CONTINUATION_MANIFEST_V1: &str = "context_continuation_manifest.v1";
pub const CONTEXT_CONTINUATION_PAYLOAD_V1: &str = "context_continuation_payload.v1";
pub const CONTEXT_CONTINUATION_RECONCILIATION_V1: &str = "context_continuation_reconciliation.v1";
pub const CONTEXT_MESH_ENVELOPE_V1: &str = "context_mesh_envelope.v1";
pub const CONTEXT_MESH_GRANT_V1: &str = "context_mesh_grant.v1";
pub const CONTEXT_MESH_IMPORT_V1: &str = "context_mesh_import.v1";
pub const CONTEXT_MESH_REVOCATION_V1: &str = "context_mesh_revocation.v1";
pub const CONTEXT_OVERFLOW_RECOVERY_V1: &str = "context_overflow_recovery.v1";
pub const CONTEXT_PACK_RESPONSE_V1: &str = "context_pack_response.v1";
pub const CONTEXT_PASSPORT_V1: &str = "context_passport.v1";
pub const CONTEXT_PASSPORT_DIFF_V1: &str = "context_passport_diff.v1";
pub const CONTEXT_PASSPORT_DIFF_VIEW_V1: &str = "context_passport_diff_view.v1";
pub const CONTEXT_PASSPORT_REPLAY_V1: &str = "context_passport_replay.v1";
pub const CONTEXT_PASSPORT_VERIFY_V1: &str = "context_passport_verify.v1";
pub const CONTEXT_POLICY_CANDIDATE_V1: &str = "context_policy_candidate.v1";
pub const CONTEXT_POLICY_EVALUATION_V1: &str = "context_policy_evaluation.v1";
pub const CONTEXT_PREP_V1: &str = "context_prep.v1";
pub const CONTEXT_PREP_ARTIFACT_V1: &str = "context_prep_artifact.v1";
pub const CONTEXTLATTICE_LIFECYCLE_RECEIPT_V1: &str = "contextlattice_lifecycle_receipt.v1";
pub const CONTINUITY_ZERO_V1: &str = "continuity_zero.v1";
pub const CONTRACT_ACKNOWLEDGEMENT_V1: &str = "contract_acknowledgement.v1";
pub const CONTRADICTION_RESOLUTION_V1: &str = "contradiction_resolution.v1";
pub const DECISION_CHANGE_V1: &str = "decision_change.v1";
pub const DECISION_CHANGE_QUERY_V1: &str = "decision_change_query.v1";
pub const DERIVED_REGRESSION_SUITE_V1: &str = "derived_regression_suite.v1";
pub const DREAM_MODE_RESPONSE_V1: &str = "dream_mode_response.v1";
pub const EVIDENCE_REPUTATION_V1: &str = "evidence_reputation.v1";
pub const FRONTIER_T10_AGGREGATE_GOVERNANCE_V1: &str = "frontier_t10_aggregate_governance.v1";
pub const FRONTIER_T10_SECURE_AGGREGATION_RESEARCH_V1: &str =
    "frontier_t10_secure_aggregation_research.v1";
pub const FRONTIER_T4_RETRIEVAL_GOVERNANCE_V1: &str = "frontier_t4_retrieval_governance.v1";
pub const FRONTIER_T5_POLICY_LABORATORY_STATUS_V1: &str = "frontier_t5_policy_laboratory_status.v1";
pub const FRONTIER_T6_AGENT_FIT_V1: &str = "frontier_t6_agent_fit.v1";
pub const FRONTIER_T6_AGENT_FIT_STATE_V1: &str = "frontier_t6_agent_fit_state.v1";
pub const FRONTIER_T6_AGENT_FIT_STATUS_V1: &str = "frontier_t6_agent_fit_status.v1";
pub const IMPORT_PLAN_V1: &str = "import_plan.v1";
pub const IMPORT_RECEIPT_V1: &str = "import_receipt.v1";
pub const MEMORY_RETIREMENT_V1: &str = "memory_retirement.v1";
pub const MEMORY_TRUST_ASSESSMENT_V1: &str = "memory_trust_assessment.v1";
pub const MODEL_SELECTION_V1: &str = "model_selection.v1";
pub const OBJECTIVE_GRAPH_V1: &str = "objective_graph.v1";
pub const OBJECTIVE_RUNTIME_STATE_V1: &str = "objective_runtime_state.v1";
pub const OBJECTIVE_TRANSITION_V1: &str = "objective_transition.v1";
pub const POLICY_CONTEXT_PACKAGE_V1: &str = "policy_context_package.v1";
pub const POLICY_PROMOTION_RECOMMENDATION_V1: &str = "policy_promotion_recommendation.v1";
pub const POLICY_SIMULATION_V1: &str = "policy_simulation.v1";
pub const PORTABLE_CONTINUATION_STATE_V1: &str = "portable_continuation_state.v1";
pub const PORTABLE_CONTINUATION_STATUS_V1: &str = "portable_continuation_status.v1";
pub const PRIVACY_ACCOUNTANT_V1: &str = "privacy_accountant.v1";
pub const PROVENANCE_V1: &str = "provenance.v1";
pub const RETRIEVAL_ABLATION_V1: &str = "retrieval_ablation.v1";
pub const RETRIEVAL_ABLATION_REPORT_V1: &str = "retrieval_ablation_report.v1";
pub const RETRIEVAL_DECISION_TRACE_V1: &str = "retrieval_decision_trace.v1";
pub const RETRIEVAL_PLAN_V1: &str = "retrieval_plan.v1";
pub const RETRIEVAL_PROGRESS_V1: &str = "retrieval_progress.v1";
pub const REUSABLE_SKILL_CANDIDATE_V1: &str = "reusable_skill_candidate.v1";
pub const REVIEW_MODE_RESPONSE_V1: &str = "review_mode_response.v1";
pub const RUN_ADVISOR_V1: &str = "run_advisor.v1";
pub const RUNNER_CAPABILITY_V1: &str = "runner_capability.v1";
pub const RUNNER_QUALITY_SAMPLE_V1: &str = "runner_quality_sample.v1";
pub const RUNNER_RESULT_V1: &str = "runner_result.v1";
pub const RUNNER_SELECTION_V1: &str = "runner_selection.v1";
pub const SCOPED_POLICY_CARD_V1: &str = "scoped_policy_card.v1";
pub const SKILL_DRAFT_V1: &str = "skill_draft.v1";
pub const SKILL_EFFICACY_REVIEW_V1: &str = "skill_efficacy_review.v1";
pub const SKILL_EVALUATION_V1: &str = "skill_evaluation.v1";
pub const SKILL_EXPORT_V1: &str = "skill_export.v1";
pub const SKILL_RETIREMENT_V1: &str = "skill_retirement.v1";
pub const SKILL_RETIREMENT_CANDIDATE_V1: &str = "skill_retirement_candidate.v1";
pub const SKILL_USAGE_RECEIPT_V1: &str = "skill_usage_receipt.v1";
pub const STEERING_COMMENT_V1: &str = "steering_comment.v1";
pub const STORAGE_TEMPERATURE_DECISION_V1: &str = "storage_temperature_decision.v1";
pub const SYNTHESIS_PACK_V1: &str = "synthesis_pack.v1";
pub const SYNTHESIS_PACK_V2: &str = "synthesis_pack.v2";
pub const TASK_IDENTITY_RECEIPT_V1: &str = "task_identity_receipt.v1";
pub const TASK_IDENTITY_RECONCILIATION_V1: &str = "task_identity_reconciliation.v1";
pub const TEMPORAL_CLAIM_V1: &str = "temporal_claim.v1";
pub const TEMPORAL_CLAIM_QUERY_V1: &str = "temporal_claim_query.v1";
pub const UNIVERSAL_AGENT_ADAPTER_RESPONSE_V1: &str = "universal_agent_adapter_response.v1";
pub const UTILITY_ANALYTICS_V1: &str = "utility_analytics.v1";
pub const UTILITY_LEDGER_V1: &str = "utility_ledger.v1";
pub const UTILITY_OBSERVATION_V1: &str = "utility_observation.v1";
pub const UTILITY_POLICY_EVALUATION_V1: &str = "utility_policy_evaluation.v1";
pub const WRITEBACK_RESULT_V1: &str = "writeback_result.v1";

pub const AGENT_CONTRACT_IDS: &[&str] = &[
    A2A_READINESS_PROFILE_V1,
    AGENT_CONTEXT_PROFILE_V1,
    AGENT_FLIGHT_RECORDER_EVENT_V1,
    AGENT_PACKET_V1,
    AGENT_PACKET_DELTA_V1,
    AGENT_PACKET_RECONSTRUCTION_V1,
    AGENT_PREFLIGHT_RESPONSE_V1,
    AGENT_PROMPT_CONTEXT_PACKAGE_V1,
    AGENT_PROOF_TIMELINE_V1,
    AGENT_RUN_TRACE_V1,
    AGENT_SESSION_ROLLUP_V1,
    AGENT_SPAN_V1,
    AGENT_TASK_LEASE_V1,
    AGENT_TASK_RESULT_V1,
    AGGREGATE_CONTRIBUTION_V1,
    AGGREGATE_REPORT_V1,
    ANTI_SCHEMING_PROTOCOL_V1,
    ASYNC_STEERING_DELIVERY_V1,
    ASYNC_STEERING_EVENT_V1,
    ASYNC_STEERING_STREAM_ITEM_V1,
    CAUSAL_BRIDGE_EXPLANATION_V1,
    CODEX_COMPACT_HOOK_STDOUT_V1,
    COLLABORATIVE_CONTEXT_GRANT_V1,
    COLLABORATIVE_CONTEXT_GRANT_DECISION_V1,
    COLLABORATIVE_CONTEXT_GRANT_REVOCATION_V1,
    CONTEXT_CONTINUATION_ENVELOPE_V1,
    CONTEXT_CONTINUATION_MANIFEST_V1,
    CONTEXT_CONTINUATION_PAYLOAD_V1,
    CONTEXT_CONTINUATION_RECONCILIATION_V1,
    CONTEXT_MESH_ENVELOPE_V1,
    CONTEXT_MESH_GRANT_V1,
    CONTEXT_MESH_IMPORT_V1,
    CONTEXT_MESH_REVOCATION_V1,
    CONTEXT_OVERFLOW_RECOVERY_V1,
    CONTEXT_PACK_RESPONSE_V1,
    CONTEXT_PASSPORT_V1,
    CONTEXT_PASSPORT_DIFF_V1,
    CONTEXT_PASSPORT_DIFF_VIEW_V1,
    CONTEXT_PASSPORT_REPLAY_V1,
    CONTEXT_PASSPORT_VERIFY_V1,
    CONTEXT_POLICY_CANDIDATE_V1,
    CONTEXT_POLICY_EVALUATION_V1,
    CONTEXT_PREP_V1,
    CONTEXT_PREP_ARTIFACT_V1,
    CONTEXTLATTICE_LIFECYCLE_RECEIPT_V1,
    CONTINUITY_ZERO_V1,
    CONTRACT_ACKNOWLEDGEMENT_V1,
    CONTRADICTION_RESOLUTION_V1,
    DECISION_CHANGE_V1,
    DECISION_CHANGE_QUERY_V1,
    DERIVED_REGRESSION_SUITE_V1,
    DREAM_MODE_RESPONSE_V1,
    EVIDENCE_REPUTATION_V1,
    FRONTIER_T10_AGGREGATE_GOVERNANCE_V1,
    FRONTIER_T10_SECURE_AGGREGATION_RESEARCH_V1,
    FRONTIER_T4_RETRIEVAL_GOVERNANCE_V1,
    FRONTIER_T5_POLICY_LABORATORY_STATUS_V1,
    FRONTIER_T6_AGENT_FIT_V1,
    FRONTIER_T6_AGENT_FIT_STATE_V1,
    FRONTIER_T6_AGENT_FIT_STATUS_V1,
    IMPORT_PLAN_V1,
    IMPORT_RECEIPT_V1,
    MEMORY_RETIREMENT_V1,
    MEMORY_TRUST_ASSESSMENT_V1,
    MODEL_SELECTION_V1,
    OBJECTIVE_GRAPH_V1,
    OBJECTIVE_RUNTIME_STATE_V1,
    OBJECTIVE_TRANSITION_V1,
    POLICY_CONTEXT_PACKAGE_V1,
    POLICY_PROMOTION_RECOMMENDATION_V1,
    POLICY_SIMULATION_V1,
    PORTABLE_CONTINUATION_STATE_V1,
    PORTABLE_CONTINUATION_STATUS_V1,
    PRIVACY_ACCOUNTANT_V1,
    PROVENANCE_V1,
    RETRIEVAL_ABLATION_V1,
    RETRIEVAL_ABLATION_REPORT_V1,
    RETRIEVAL_DECISION_TRACE_V1,
    RETRIEVAL_PLAN_V1,
    RETRIEVAL_PROGRESS_V1,
    REUSABLE_SKILL_CANDIDATE_V1,
    REVIEW_MODE_RESPONSE_V1,
    RUN_ADVISOR_V1,
    RUNNER_CAPABILITY_V1,
    RUNNER_QUALITY_SAMPLE_V1,
    RUNNER_RESULT_V1,
    RUNNER_SELECTION_V1,
    SCOPED_POLICY_CARD_V1,
    SKILL_DRAFT_V1,
    SKILL_EFFICACY_REVIEW_V1,
    SKILL_EVALUATION_V1,
    SKILL_EXPORT_V1,
    SKILL_RETIREMENT_V1,
    SKILL_RETIREMENT_CANDIDATE_V1,
    SKILL_USAGE_RECEIPT_V1,
    STEERING_COMMENT_V1,
    STORAGE_TEMPERATURE_DECISION_V1,
    SYNTHESIS_PACK_V1,
    SYNTHESIS_PACK_V2,
    TASK_IDENTITY_RECEIPT_V1,
    TASK_IDENTITY_RECONCILIATION_V1,
    TEMPORAL_CLAIM_V1,
    TEMPORAL_CLAIM_QUERY_V1,
    UNIVERSAL_AGENT_ADAPTER_RESPONSE_V1,
    UTILITY_ANALYTICS_V1,
    UTILITY_LEDGER_V1,
    UTILITY_OBSERVATION_V1,
    UTILITY_POLICY_EVALUATION_V1,
    WRITEBACK_RESULT_V1,
];

pub const AGENT_CONTRACTS: &[AgentContractRef] = &[
    AgentContractRef {
        schema_id: A2A_READINESS_PROFILE_V1,
        payload_kind: "a2a_readiness_profile",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_CONTEXT_PROFILE_V1,
        payload_kind: "effective_agent_context_profile",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_FLIGHT_RECORDER_EVENT_V1,
        payload_kind: "agent_flight_recorder_event",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_PACKET_V1,
        payload_kind: "compact_prompt_ready_agent_packet",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_PACKET_DELTA_V1,
        payload_kind: "deterministic_agent_packet_delta",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_PACKET_RECONSTRUCTION_V1,
        payload_kind: "verified_agent_packet_reconstruction",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_PREFLIGHT_RESPONSE_V1,
        payload_kind: "agent_preflight_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_PROMPT_CONTEXT_PACKAGE_V1,
        payload_kind: "agent_prompt_context_package",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_PROOF_TIMELINE_V1,
        payload_kind: "agent_proof_timeline",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_RUN_TRACE_V1,
        payload_kind: "agent_run_trace",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_SESSION_ROLLUP_V1,
        payload_kind: "agent_session_rollup",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_SPAN_V1,
        payload_kind: "agent_span",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_TASK_LEASE_V1,
        payload_kind: "agent_task_lease",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGENT_TASK_RESULT_V1,
        payload_kind: "agent_task_result",
        contract_version: 1,
        required_output_mode: "json_object_or_markdown_with_json_frontmatter",
    },
    AgentContractRef {
        schema_id: AGGREGATE_CONTRIBUTION_V1,
        payload_kind: "opt_in_bounded_local_aggregate_contribution",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: AGGREGATE_REPORT_V1,
        payload_kind: "cohort_suppressed_idempotent_noisy_aggregate_report",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: ANTI_SCHEMING_PROTOCOL_V1,
        payload_kind: "policy_fragment",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: ASYNC_STEERING_DELIVERY_V1,
        payload_kind: "durable_async_steering_delivery_receipt",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: ASYNC_STEERING_EVENT_V1,
        payload_kind: "durable_async_steering_event",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: ASYNC_STEERING_STREAM_ITEM_V1,
        payload_kind: "resumable_async_steering_stream_item",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CAUSAL_BRIDGE_EXPLANATION_V1,
        payload_kind: "bounded_proof_carrying_cross_project_causal_bridge_explanation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CODEX_COMPACT_HOOK_STDOUT_V1,
        payload_kind: "codex_compact_hook_stdout",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: COLLABORATIVE_CONTEXT_GRANT_V1,
        payload_kind: "signed_bounded_least_privilege_collaborative_context_grant",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: COLLABORATIVE_CONTEXT_GRANT_DECISION_V1,
        payload_kind: "bounded_digest_bound_collaborative_context_grant_decision",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: COLLABORATIVE_CONTEXT_GRANT_REVOCATION_V1,
        payload_kind: "signed_digest_only_collaborative_context_grant_revocation_tombstone",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_CONTINUATION_ENVELOPE_V1,
        payload_kind: "bounded_transport_neutral_encrypted_mesh_continuation_envelope",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_CONTINUATION_MANIFEST_V1,
        payload_kind: "signed_bounded_digest_only_portable_context_continuation_manifest",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_CONTINUATION_PAYLOAD_V1,
        payload_kind: "signed_bounded_redacted_digest_only_mesh_continuation_payload",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_CONTINUATION_RECONCILIATION_V1,
        payload_kind: "bounded_dry_run_portable_context_continuation_reconciliation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_MESH_ENVELOPE_V1,
        payload_kind: "transport_neutral_encrypted_context_envelope",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_MESH_GRANT_V1,
        payload_kind: "signed_project_scoped_mesh_grant",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_MESH_IMPORT_V1,
        payload_kind: "verified_context_mesh_reconciliation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_MESH_REVOCATION_V1,
        payload_kind: "signed_local_mesh_revocation_tombstone",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_OVERFLOW_RECOVERY_V1,
        payload_kind: "context_overflow_recovery",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_PACK_RESPONSE_V1,
        payload_kind: "context_pack_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_PASSPORT_V1,
        payload_kind: "signed_replayable_context_passport",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_PASSPORT_DIFF_V1,
        payload_kind: "context_passport_diff",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_PASSPORT_DIFF_VIEW_V1,
        payload_kind: "bounded_deterministic_redacted_context_passport_diff_view",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_PASSPORT_REPLAY_V1,
        payload_kind: "context_passport_replay_plan",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_PASSPORT_VERIFY_V1,
        payload_kind: "context_passport_verification",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_POLICY_CANDIDATE_V1,
        payload_kind: "outcome_trained_context_policy_candidate",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_POLICY_EVALUATION_V1,
        payload_kind: "context_policy_canary_evaluation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_PREP_V1,
        payload_kind: "opt_in_external_worker_context_preparation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXT_PREP_ARTIFACT_V1,
        payload_kind: "bounded_prepared_context_artifact_reference",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTEXTLATTICE_LIFECYCLE_RECEIPT_V1,
        payload_kind: "contextlattice_lifecycle_receipt",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTINUITY_ZERO_V1,
        payload_kind: "path_free_fail_closed_zero_entry_continuity_manifest",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTRACT_ACKNOWLEDGEMENT_V1,
        payload_kind: "contract_acknowledgement",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: CONTRADICTION_RESOLUTION_V1,
        payload_kind: "append_only_evidence_weighted_contradiction_resolution_and_appeal",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: DECISION_CHANGE_V1,
        payload_kind: "decision_change",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: DECISION_CHANGE_QUERY_V1,
        payload_kind: "decision_change_query",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: DERIVED_REGRESSION_SUITE_V1,
        payload_kind: "immutable_review_only_derived_retrieval_regression_proposals",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: DREAM_MODE_RESPONSE_V1,
        payload_kind: "dream_mode_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: EVIDENCE_REPUTATION_V1,
        payload_kind: "advisory_calibrated_evidence_reputation_projection",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: FRONTIER_T10_AGGREGATE_GOVERNANCE_V1,
        payload_kind: "entitlement_gated_opt_in_workspace_cohort_aggregation_governance",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: FRONTIER_T10_SECURE_AGGREGATION_RESEARCH_V1,
        payload_kind: "private_keyless_secure_aggregation_research_and_attack_review_gate",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: FRONTIER_T4_RETRIEVAL_GOVERNANCE_V1,
        payload_kind: "entitled_bounded_retrieval_receipt_policy_and_operations_governance",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: FRONTIER_T5_POLICY_LABORATORY_STATUS_V1,
        payload_kind: "bounded_policy_laboratory_runtime_status",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: FRONTIER_T6_AGENT_FIT_V1,
        payload_kind: "bounded_agent_fit_operation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: FRONTIER_T6_AGENT_FIT_STATE_V1,
        payload_kind: "bounded_owner_only_agent_fit_state",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: FRONTIER_T6_AGENT_FIT_STATUS_V1,
        payload_kind: "bounded_agent_fit_runtime_status",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: IMPORT_PLAN_V1,
        payload_kind: "bounded_redacted_digest_only_external_worker_import_plan",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: IMPORT_RECEIPT_V1,
        payload_kind: "bounded_atomic_resumable_external_import_receipt",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: MEMORY_RETIREMENT_V1,
        payload_kind: "non_destructive_reversible_memory_retirement_workflow",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: MEMORY_TRUST_ASSESSMENT_V1,
        payload_kind: "bounded_retrieval_memory_trust_assessment",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: MODEL_SELECTION_V1,
        payload_kind: "advisor_only_model_selection_receipt",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: OBJECTIVE_GRAPH_V1,
        payload_kind: "longitudinal_objective_graph",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: OBJECTIVE_RUNTIME_STATE_V1,
        payload_kind: "objective_runtime_state",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: OBJECTIVE_TRANSITION_V1,
        payload_kind: "objective_transition",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: POLICY_CONTEXT_PACKAGE_V1,
        payload_kind: "agent_policy_context_package",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: POLICY_PROMOTION_RECOMMENDATION_V1,
        payload_kind: "assignment_bound_uncertainty_aware_policy_promotion_recommendation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: POLICY_SIMULATION_V1,
        payload_kind: "same_snapshot_no_persist_retrieval_policy_simulation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: PORTABLE_CONTINUATION_STATE_V1,
        payload_kind: "bounded_owner_only_redacted_digest_reference_portable_continuation_state",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: PORTABLE_CONTINUATION_STATUS_V1,
        payload_kind: "bounded_redacted_digest_only_portable_continuation_runtime_status",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: PRIVACY_ACCOUNTANT_V1,
        payload_kind: "bounded_local_aggregate_privacy_accountant_and_expiry_receipts",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: PROVENANCE_V1,
        payload_kind: "bounded_redacted_digest_only_external_import_provenance",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RETRIEVAL_ABLATION_V1,
        payload_kind: "same_snapshot_leave_one_evidence_retrieval_ablation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RETRIEVAL_ABLATION_REPORT_V1,
        payload_kind: "bounded_retrieval_ablation_summary",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RETRIEVAL_DECISION_TRACE_V1,
        payload_kind: "bounded_retrieval_decision_receipt_trace",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RETRIEVAL_PLAN_V1,
        payload_kind: "adaptive_retrieval_plan",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RETRIEVAL_PROGRESS_V1,
        payload_kind: "retrieval_progress",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: REUSABLE_SKILL_CANDIDATE_V1,
        payload_kind: "inactive_verified_reusable_skill_candidate",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: REVIEW_MODE_RESPONSE_V1,
        payload_kind: "review_mode_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RUN_ADVISOR_V1,
        payload_kind: "run_advisor",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RUNNER_CAPABILITY_V1,
        payload_kind: "runner_capability",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RUNNER_QUALITY_SAMPLE_V1,
        payload_kind: "runner_quality_sample",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RUNNER_RESULT_V1,
        payload_kind: "runner_result",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: RUNNER_SELECTION_V1,
        payload_kind: "advisor_only_runner_selection_receipt",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SCOPED_POLICY_CARD_V1,
        payload_kind: "project_task_and_intent_scoped_retrieval_policy_card",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SKILL_DRAFT_V1,
        payload_kind: "verified_workflow_skill_draft",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SKILL_EFFICACY_REVIEW_V1,
        payload_kind: "inactive_skill_efficacy_review",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SKILL_EVALUATION_V1,
        payload_kind: "independent_skill_holdout_evaluation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SKILL_EXPORT_V1,
        payload_kind: "human_approved_inactive_skill_export",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SKILL_RETIREMENT_V1,
        payload_kind: "explicit_inactive_skill_draft_retirement",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SKILL_RETIREMENT_CANDIDATE_V1,
        payload_kind: "advisory_skill_retirement_candidate",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SKILL_USAGE_RECEIPT_V1,
        payload_kind: "append_only_skill_usage_receipt",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: STEERING_COMMENT_V1,
        payload_kind: "steering_comment",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: STORAGE_TEMPERATURE_DECISION_V1,
        payload_kind: "utility_based_reversible_memory_storage_temperature_decision",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SYNTHESIS_PACK_V1,
        payload_kind: "synthesis_pack",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: SYNTHESIS_PACK_V2,
        payload_kind: "proof_carrying_synthesis_pack",
        contract_version: 2,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: TASK_IDENTITY_RECEIPT_V1,
        payload_kind: "task_identity_receipt",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: TASK_IDENTITY_RECONCILIATION_V1,
        payload_kind: "task_identity_reconciliation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: TEMPORAL_CLAIM_V1,
        payload_kind: "temporal_claim",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: TEMPORAL_CLAIM_QUERY_V1,
        payload_kind: "temporal_claim_query",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: UNIVERSAL_AGENT_ADAPTER_RESPONSE_V1,
        payload_kind: "universal_agent_adapter_response",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: UTILITY_ANALYTICS_V1,
        payload_kind: "entitled_continuous_utility_cohort_analytics",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: UTILITY_LEDGER_V1,
        payload_kind: "bounded_verified_utility_ledger",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: UTILITY_OBSERVATION_V1,
        payload_kind: "verified_utility_observation",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: UTILITY_POLICY_EVALUATION_V1,
        payload_kind: "entitled_advisory_verified_utility_policy_gate",
        contract_version: 1,
        required_output_mode: "json_object",
    },
    AgentContractRef {
        schema_id: WRITEBACK_RESULT_V1,
        payload_kind: "writeback_result",
        contract_version: 1,
        required_output_mode: "json_object",
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_contracts_are_present() {
        assert_eq!(
            AGENT_CONTRACT_REGISTRY_ID,
            "contextlattice_agent_output_contracts"
        );
        assert_eq!(AGENT_CONTRACT_IDS.len(), AGENT_CONTRACTS.len());
        assert!(AGENT_CONTRACT_IDS.contains(&POLICY_CONTEXT_PACKAGE_V1));
        assert!(AGENT_CONTRACT_IDS.contains(&A2A_READINESS_PROFILE_V1));
        assert!(AGENT_CONTRACT_IDS.contains(&CONTEXT_OVERFLOW_RECOVERY_V1));
    }
}
