// Code generated by scripts/agent/generate-agent-contract-types; DO NOT EDIT.

package main

const generatedAgentContractRegistryID = "contextlattice_agent_output_contracts"
const generatedAgentContractRegistryVersion = 49
const generatedLifecycleReceiptContractID = "contextlattice_lifecycle_receipt.v1"
