// Code generated by scripts/agent/generate-agent-contract-types; DO NOT EDIT.

package main

type GeneratedAgentContractRef struct {
	SchemaID           string
	PayloadKind        string
	ContractVersion    int
	RequiredOutputMode string
}

const GeneratedAgentContractRegistryID = "contextlattice_agent_output_contracts"
const GeneratedAgentContractRegistryVersion = 52

const GeneratedAgentContractA2aReadinessProfileV1 = "a2a_readiness_profile.v1"
const GeneratedAgentContractAgentContextProfileV1 = "agent_context_profile.v1"
const GeneratedAgentContractAgentFlightRecorderEventV1 = "agent_flight_recorder_event.v1"
const GeneratedAgentContractAgentPacketV1 = "agent_packet.v1"
const GeneratedAgentContractAgentPacketDeltaV1 = "agent_packet_delta.v1"
const GeneratedAgentContractAgentPacketReconstructionV1 = "agent_packet_reconstruction.v1"
const GeneratedAgentContractAgentPreflightResponseV1 = "agent_preflight_response.v1"
const GeneratedAgentContractAgentPromptContextPackageV1 = "agent_prompt_context_package.v1"
const GeneratedAgentContractAgentProofTimelineV1 = "agent_proof_timeline.v1"
const GeneratedAgentContractAgentRunTraceV1 = "agent_run_trace.v1"
const GeneratedAgentContractAgentSessionRollupV1 = "agent_session_rollup.v1"
const GeneratedAgentContractAgentSpanV1 = "agent_span.v1"
const GeneratedAgentContractAgentTaskLeaseV1 = "agent_task_lease.v1"
const GeneratedAgentContractAgentTaskResultV1 = "agent_task_result.v1"
const GeneratedAgentContractAntiSchemingProtocolV1 = "anti_scheming_protocol.v1"
const GeneratedAgentContractAsyncSteeringDeliveryV1 = "async_steering_delivery.v1"
const GeneratedAgentContractAsyncSteeringEventV1 = "async_steering_event.v1"
const GeneratedAgentContractAsyncSteeringStreamItemV1 = "async_steering_stream_item.v1"
const GeneratedAgentContractCausalBridgeExplanationV1 = "causal_bridge_explanation.v1"
const GeneratedAgentContractCodexCompactHookStdoutV1 = "codex_compact_hook_stdout.v1"
const GeneratedAgentContractCollaborativeContextGrantV1 = "collaborative_context_grant.v1"
const GeneratedAgentContractCollaborativeContextGrantDecisionV1 = "collaborative_context_grant_decision.v1"
const GeneratedAgentContractCollaborativeContextGrantRevocationV1 = "collaborative_context_grant_revocation.v1"
const GeneratedAgentContractContextContinuationEnvelopeV1 = "context_continuation_envelope.v1"
const GeneratedAgentContractContextContinuationManifestV1 = "context_continuation_manifest.v1"
const GeneratedAgentContractContextContinuationPayloadV1 = "context_continuation_payload.v1"
const GeneratedAgentContractContextContinuationReconciliationV1 = "context_continuation_reconciliation.v1"
const GeneratedAgentContractContextMeshEnvelopeV1 = "context_mesh_envelope.v1"
const GeneratedAgentContractContextMeshGrantV1 = "context_mesh_grant.v1"
const GeneratedAgentContractContextMeshImportV1 = "context_mesh_import.v1"
const GeneratedAgentContractContextMeshRevocationV1 = "context_mesh_revocation.v1"
const GeneratedAgentContractContextOverflowRecoveryV1 = "context_overflow_recovery.v1"
const GeneratedAgentContractContextPackResponseV1 = "context_pack_response.v1"
const GeneratedAgentContractContextPassportV1 = "context_passport.v1"
const GeneratedAgentContractContextPassportDiffV1 = "context_passport_diff.v1"
const GeneratedAgentContractContextPassportDiffViewV1 = "context_passport_diff_view.v1"
const GeneratedAgentContractContextPassportReplayV1 = "context_passport_replay.v1"
const GeneratedAgentContractContextPassportVerifyV1 = "context_passport_verify.v1"
const GeneratedAgentContractContextPolicyCandidateV1 = "context_policy_candidate.v1"
const GeneratedAgentContractContextPolicyEvaluationV1 = "context_policy_evaluation.v1"
const GeneratedAgentContractContextPrepV1 = "context_prep.v1"
const GeneratedAgentContractContextPrepArtifactV1 = "context_prep_artifact.v1"
const GeneratedAgentContractContextlatticeLifecycleReceiptV1 = "contextlattice_lifecycle_receipt.v1"
const GeneratedAgentContractContinuityZeroV1 = "continuity_zero.v1"
const GeneratedAgentContractContractAcknowledgementV1 = "contract_acknowledgement.v1"
const GeneratedAgentContractContradictionResolutionV1 = "contradiction_resolution.v1"
const GeneratedAgentContractDecisionChangeV1 = "decision_change.v1"
const GeneratedAgentContractDecisionChangeQueryV1 = "decision_change_query.v1"
const GeneratedAgentContractDerivedRegressionSuiteV1 = "derived_regression_suite.v1"
const GeneratedAgentContractDreamModeResponseV1 = "dream_mode_response.v1"
const GeneratedAgentContractEvidenceReputationV1 = "evidence_reputation.v1"
const GeneratedAgentContractFrontierT4RetrievalGovernanceV1 = "frontier_t4_retrieval_governance.v1"
const GeneratedAgentContractFrontierT5PolicyLaboratoryStatusV1 = "frontier_t5_policy_laboratory_status.v1"
const GeneratedAgentContractFrontierT6AgentFitV1 = "frontier_t6_agent_fit.v1"
const GeneratedAgentContractFrontierT6AgentFitStateV1 = "frontier_t6_agent_fit_state.v1"
const GeneratedAgentContractFrontierT6AgentFitStatusV1 = "frontier_t6_agent_fit_status.v1"
const GeneratedAgentContractImportPlanV1 = "import_plan.v1"
const GeneratedAgentContractImportReceiptV1 = "import_receipt.v1"
const GeneratedAgentContractMemoryRetirementV1 = "memory_retirement.v1"
const GeneratedAgentContractMemoryTrustAssessmentV1 = "memory_trust_assessment.v1"
const GeneratedAgentContractModelSelectionV1 = "model_selection.v1"
const GeneratedAgentContractObjectiveGraphV1 = "objective_graph.v1"
const GeneratedAgentContractObjectiveRuntimeStateV1 = "objective_runtime_state.v1"
const GeneratedAgentContractObjectiveTransitionV1 = "objective_transition.v1"
const GeneratedAgentContractPolicyContextPackageV1 = "policy_context_package.v1"
const GeneratedAgentContractPolicyPromotionRecommendationV1 = "policy_promotion_recommendation.v1"
const GeneratedAgentContractPolicySimulationV1 = "policy_simulation.v1"
const GeneratedAgentContractPortableContinuationStateV1 = "portable_continuation_state.v1"
const GeneratedAgentContractPortableContinuationStatusV1 = "portable_continuation_status.v1"
const GeneratedAgentContractProvenanceV1 = "provenance.v1"
const GeneratedAgentContractRetrievalAblationV1 = "retrieval_ablation.v1"
const GeneratedAgentContractRetrievalAblationReportV1 = "retrieval_ablation_report.v1"
const GeneratedAgentContractRetrievalDecisionTraceV1 = "retrieval_decision_trace.v1"
const GeneratedAgentContractRetrievalPlanV1 = "retrieval_plan.v1"
const GeneratedAgentContractRetrievalProgressV1 = "retrieval_progress.v1"
const GeneratedAgentContractReusableSkillCandidateV1 = "reusable_skill_candidate.v1"
const GeneratedAgentContractReviewModeResponseV1 = "review_mode_response.v1"
const GeneratedAgentContractRunAdvisorV1 = "run_advisor.v1"
const GeneratedAgentContractRunnerCapabilityV1 = "runner_capability.v1"
const GeneratedAgentContractRunnerQualitySampleV1 = "runner_quality_sample.v1"
const GeneratedAgentContractRunnerResultV1 = "runner_result.v1"
const GeneratedAgentContractRunnerSelectionV1 = "runner_selection.v1"
const GeneratedAgentContractScopedPolicyCardV1 = "scoped_policy_card.v1"
const GeneratedAgentContractSkillDraftV1 = "skill_draft.v1"
const GeneratedAgentContractSkillEvaluationV1 = "skill_evaluation.v1"
const GeneratedAgentContractSkillExportV1 = "skill_export.v1"
const GeneratedAgentContractSkillRetirementV1 = "skill_retirement.v1"
const GeneratedAgentContractSkillRetirementCandidateV1 = "skill_retirement_candidate.v1"
const GeneratedAgentContractSteeringCommentV1 = "steering_comment.v1"
const GeneratedAgentContractStorageTemperatureDecisionV1 = "storage_temperature_decision.v1"
const GeneratedAgentContractSynthesisPackV1 = "synthesis_pack.v1"
const GeneratedAgentContractSynthesisPackV2 = "synthesis_pack.v2"
const GeneratedAgentContractTaskIdentityReceiptV1 = "task_identity_receipt.v1"
const GeneratedAgentContractTaskIdentityReconciliationV1 = "task_identity_reconciliation.v1"
const GeneratedAgentContractTemporalClaimV1 = "temporal_claim.v1"
const GeneratedAgentContractTemporalClaimQueryV1 = "temporal_claim_query.v1"
const GeneratedAgentContractUniversalAgentAdapterResponseV1 = "universal_agent_adapter_response.v1"
const GeneratedAgentContractUtilityAnalyticsV1 = "utility_analytics.v1"
const GeneratedAgentContractUtilityLedgerV1 = "utility_ledger.v1"
const GeneratedAgentContractUtilityObservationV1 = "utility_observation.v1"
const GeneratedAgentContractUtilityPolicyEvaluationV1 = "utility_policy_evaluation.v1"
const GeneratedAgentContractWritebackResultV1 = "writeback_result.v1"

var GeneratedAgentContractIDs = []string{
	GeneratedAgentContractA2aReadinessProfileV1,
	GeneratedAgentContractAgentContextProfileV1,
	GeneratedAgentContractAgentFlightRecorderEventV1,
	GeneratedAgentContractAgentPacketV1,
	GeneratedAgentContractAgentPacketDeltaV1,
	GeneratedAgentContractAgentPacketReconstructionV1,
	GeneratedAgentContractAgentPreflightResponseV1,
	GeneratedAgentContractAgentPromptContextPackageV1,
	GeneratedAgentContractAgentProofTimelineV1,
	GeneratedAgentContractAgentRunTraceV1,
	GeneratedAgentContractAgentSessionRollupV1,
	GeneratedAgentContractAgentSpanV1,
	GeneratedAgentContractAgentTaskLeaseV1,
	GeneratedAgentContractAgentTaskResultV1,
	GeneratedAgentContractAntiSchemingProtocolV1,
	GeneratedAgentContractAsyncSteeringDeliveryV1,
	GeneratedAgentContractAsyncSteeringEventV1,
	GeneratedAgentContractAsyncSteeringStreamItemV1,
	GeneratedAgentContractCausalBridgeExplanationV1,
	GeneratedAgentContractCodexCompactHookStdoutV1,
	GeneratedAgentContractCollaborativeContextGrantV1,
	GeneratedAgentContractCollaborativeContextGrantDecisionV1,
	GeneratedAgentContractCollaborativeContextGrantRevocationV1,
	GeneratedAgentContractContextContinuationEnvelopeV1,
	GeneratedAgentContractContextContinuationManifestV1,
	GeneratedAgentContractContextContinuationPayloadV1,
	GeneratedAgentContractContextContinuationReconciliationV1,
	GeneratedAgentContractContextMeshEnvelopeV1,
	GeneratedAgentContractContextMeshGrantV1,
	GeneratedAgentContractContextMeshImportV1,
	GeneratedAgentContractContextMeshRevocationV1,
	GeneratedAgentContractContextOverflowRecoveryV1,
	GeneratedAgentContractContextPackResponseV1,
	GeneratedAgentContractContextPassportV1,
	GeneratedAgentContractContextPassportDiffV1,
	GeneratedAgentContractContextPassportDiffViewV1,
	GeneratedAgentContractContextPassportReplayV1,
	GeneratedAgentContractContextPassportVerifyV1,
	GeneratedAgentContractContextPolicyCandidateV1,
	GeneratedAgentContractContextPolicyEvaluationV1,
	GeneratedAgentContractContextPrepV1,
	GeneratedAgentContractContextPrepArtifactV1,
	GeneratedAgentContractContextlatticeLifecycleReceiptV1,
	GeneratedAgentContractContinuityZeroV1,
	GeneratedAgentContractContractAcknowledgementV1,
	GeneratedAgentContractContradictionResolutionV1,
	GeneratedAgentContractDecisionChangeV1,
	GeneratedAgentContractDecisionChangeQueryV1,
	GeneratedAgentContractDerivedRegressionSuiteV1,
	GeneratedAgentContractDreamModeResponseV1,
	GeneratedAgentContractEvidenceReputationV1,
	GeneratedAgentContractFrontierT4RetrievalGovernanceV1,
	GeneratedAgentContractFrontierT5PolicyLaboratoryStatusV1,
	GeneratedAgentContractFrontierT6AgentFitV1,
	GeneratedAgentContractFrontierT6AgentFitStateV1,
	GeneratedAgentContractFrontierT6AgentFitStatusV1,
	GeneratedAgentContractImportPlanV1,
	GeneratedAgentContractImportReceiptV1,
	GeneratedAgentContractMemoryRetirementV1,
	GeneratedAgentContractMemoryTrustAssessmentV1,
	GeneratedAgentContractModelSelectionV1,
	GeneratedAgentContractObjectiveGraphV1,
	GeneratedAgentContractObjectiveRuntimeStateV1,
	GeneratedAgentContractObjectiveTransitionV1,
	GeneratedAgentContractPolicyContextPackageV1,
	GeneratedAgentContractPolicyPromotionRecommendationV1,
	GeneratedAgentContractPolicySimulationV1,
	GeneratedAgentContractPortableContinuationStateV1,
	GeneratedAgentContractPortableContinuationStatusV1,
	GeneratedAgentContractProvenanceV1,
	GeneratedAgentContractRetrievalAblationV1,
	GeneratedAgentContractRetrievalAblationReportV1,
	GeneratedAgentContractRetrievalDecisionTraceV1,
	GeneratedAgentContractRetrievalPlanV1,
	GeneratedAgentContractRetrievalProgressV1,
	GeneratedAgentContractReusableSkillCandidateV1,
	GeneratedAgentContractReviewModeResponseV1,
	GeneratedAgentContractRunAdvisorV1,
	GeneratedAgentContractRunnerCapabilityV1,
	GeneratedAgentContractRunnerQualitySampleV1,
	GeneratedAgentContractRunnerResultV1,
	GeneratedAgentContractRunnerSelectionV1,
	GeneratedAgentContractScopedPolicyCardV1,
	GeneratedAgentContractSkillDraftV1,
	GeneratedAgentContractSkillEvaluationV1,
	GeneratedAgentContractSkillExportV1,
	GeneratedAgentContractSkillRetirementV1,
	GeneratedAgentContractSkillRetirementCandidateV1,
	GeneratedAgentContractSteeringCommentV1,
	GeneratedAgentContractStorageTemperatureDecisionV1,
	GeneratedAgentContractSynthesisPackV1,
	GeneratedAgentContractSynthesisPackV2,
	GeneratedAgentContractTaskIdentityReceiptV1,
	GeneratedAgentContractTaskIdentityReconciliationV1,
	GeneratedAgentContractTemporalClaimV1,
	GeneratedAgentContractTemporalClaimQueryV1,
	GeneratedAgentContractUniversalAgentAdapterResponseV1,
	GeneratedAgentContractUtilityAnalyticsV1,
	GeneratedAgentContractUtilityLedgerV1,
	GeneratedAgentContractUtilityObservationV1,
	GeneratedAgentContractUtilityPolicyEvaluationV1,
	GeneratedAgentContractWritebackResultV1,
}

var GeneratedAgentContracts = []GeneratedAgentContractRef{
	{
		SchemaID:           GeneratedAgentContractA2aReadinessProfileV1,
		PayloadKind:        "a2a_readiness_profile",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentContextProfileV1,
		PayloadKind:        "effective_agent_context_profile",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentFlightRecorderEventV1,
		PayloadKind:        "agent_flight_recorder_event",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPacketV1,
		PayloadKind:        "compact_prompt_ready_agent_packet",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPacketDeltaV1,
		PayloadKind:        "deterministic_agent_packet_delta",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPacketReconstructionV1,
		PayloadKind:        "verified_agent_packet_reconstruction",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPreflightResponseV1,
		PayloadKind:        "agent_preflight_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPromptContextPackageV1,
		PayloadKind:        "agent_prompt_context_package",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentProofTimelineV1,
		PayloadKind:        "agent_proof_timeline",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentRunTraceV1,
		PayloadKind:        "agent_run_trace",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentSessionRollupV1,
		PayloadKind:        "agent_session_rollup",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentSpanV1,
		PayloadKind:        "agent_span",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentTaskLeaseV1,
		PayloadKind:        "agent_task_lease",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentTaskResultV1,
		PayloadKind:        "agent_task_result",
		ContractVersion:    1,
		RequiredOutputMode: "json_object_or_markdown_with_json_frontmatter",
	},
	{
		SchemaID:           GeneratedAgentContractAntiSchemingProtocolV1,
		PayloadKind:        "policy_fragment",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAsyncSteeringDeliveryV1,
		PayloadKind:        "durable_async_steering_delivery_receipt",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAsyncSteeringEventV1,
		PayloadKind:        "durable_async_steering_event",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAsyncSteeringStreamItemV1,
		PayloadKind:        "resumable_async_steering_stream_item",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractCausalBridgeExplanationV1,
		PayloadKind:        "bounded_proof_carrying_cross_project_causal_bridge_explanation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractCodexCompactHookStdoutV1,
		PayloadKind:        "codex_compact_hook_stdout",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractCollaborativeContextGrantV1,
		PayloadKind:        "signed_bounded_least_privilege_collaborative_context_grant",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractCollaborativeContextGrantDecisionV1,
		PayloadKind:        "bounded_digest_bound_collaborative_context_grant_decision",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractCollaborativeContextGrantRevocationV1,
		PayloadKind:        "signed_digest_only_collaborative_context_grant_revocation_tombstone",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextContinuationEnvelopeV1,
		PayloadKind:        "bounded_transport_neutral_encrypted_mesh_continuation_envelope",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextContinuationManifestV1,
		PayloadKind:        "signed_bounded_digest_only_portable_context_continuation_manifest",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextContinuationPayloadV1,
		PayloadKind:        "signed_bounded_redacted_digest_only_mesh_continuation_payload",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextContinuationReconciliationV1,
		PayloadKind:        "bounded_dry_run_portable_context_continuation_reconciliation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextMeshEnvelopeV1,
		PayloadKind:        "transport_neutral_encrypted_context_envelope",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextMeshGrantV1,
		PayloadKind:        "signed_project_scoped_mesh_grant",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextMeshImportV1,
		PayloadKind:        "verified_context_mesh_reconciliation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextMeshRevocationV1,
		PayloadKind:        "signed_local_mesh_revocation_tombstone",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextOverflowRecoveryV1,
		PayloadKind:        "context_overflow_recovery",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPackResponseV1,
		PayloadKind:        "context_pack_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPassportV1,
		PayloadKind:        "signed_replayable_context_passport",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPassportDiffV1,
		PayloadKind:        "context_passport_diff",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPassportDiffViewV1,
		PayloadKind:        "bounded_deterministic_redacted_context_passport_diff_view",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPassportReplayV1,
		PayloadKind:        "context_passport_replay_plan",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPassportVerifyV1,
		PayloadKind:        "context_passport_verification",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPolicyCandidateV1,
		PayloadKind:        "outcome_trained_context_policy_candidate",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPolicyEvaluationV1,
		PayloadKind:        "context_policy_canary_evaluation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPrepV1,
		PayloadKind:        "opt_in_external_worker_context_preparation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPrepArtifactV1,
		PayloadKind:        "bounded_prepared_context_artifact_reference",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextlatticeLifecycleReceiptV1,
		PayloadKind:        "contextlattice_lifecycle_receipt",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContinuityZeroV1,
		PayloadKind:        "path_free_fail_closed_zero_entry_continuity_manifest",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContractAcknowledgementV1,
		PayloadKind:        "contract_acknowledgement",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContradictionResolutionV1,
		PayloadKind:        "append_only_evidence_weighted_contradiction_resolution_and_appeal",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractDecisionChangeV1,
		PayloadKind:        "decision_change",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractDecisionChangeQueryV1,
		PayloadKind:        "decision_change_query",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractDerivedRegressionSuiteV1,
		PayloadKind:        "immutable_review_only_derived_retrieval_regression_proposals",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractDreamModeResponseV1,
		PayloadKind:        "dream_mode_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractEvidenceReputationV1,
		PayloadKind:        "advisory_calibrated_evidence_reputation_projection",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractFrontierT4RetrievalGovernanceV1,
		PayloadKind:        "entitled_bounded_retrieval_receipt_policy_and_operations_governance",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractFrontierT5PolicyLaboratoryStatusV1,
		PayloadKind:        "bounded_policy_laboratory_runtime_status",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractFrontierT6AgentFitV1,
		PayloadKind:        "bounded_agent_fit_operation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractFrontierT6AgentFitStateV1,
		PayloadKind:        "bounded_owner_only_agent_fit_state",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractFrontierT6AgentFitStatusV1,
		PayloadKind:        "bounded_agent_fit_runtime_status",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractImportPlanV1,
		PayloadKind:        "bounded_redacted_digest_only_external_worker_import_plan",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractImportReceiptV1,
		PayloadKind:        "bounded_atomic_resumable_external_import_receipt",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractMemoryRetirementV1,
		PayloadKind:        "non_destructive_reversible_memory_retirement_workflow",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractMemoryTrustAssessmentV1,
		PayloadKind:        "bounded_retrieval_memory_trust_assessment",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractModelSelectionV1,
		PayloadKind:        "advisor_only_model_selection_receipt",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractObjectiveGraphV1,
		PayloadKind:        "longitudinal_objective_graph",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractObjectiveRuntimeStateV1,
		PayloadKind:        "objective_runtime_state",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractObjectiveTransitionV1,
		PayloadKind:        "objective_transition",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractPolicyContextPackageV1,
		PayloadKind:        "agent_policy_context_package",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractPolicyPromotionRecommendationV1,
		PayloadKind:        "assignment_bound_uncertainty_aware_policy_promotion_recommendation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractPolicySimulationV1,
		PayloadKind:        "same_snapshot_no_persist_retrieval_policy_simulation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractPortableContinuationStateV1,
		PayloadKind:        "bounded_owner_only_redacted_digest_reference_portable_continuation_state",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractPortableContinuationStatusV1,
		PayloadKind:        "bounded_redacted_digest_only_portable_continuation_runtime_status",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractProvenanceV1,
		PayloadKind:        "bounded_redacted_digest_only_external_import_provenance",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRetrievalAblationV1,
		PayloadKind:        "same_snapshot_leave_one_evidence_retrieval_ablation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRetrievalAblationReportV1,
		PayloadKind:        "bounded_retrieval_ablation_summary",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRetrievalDecisionTraceV1,
		PayloadKind:        "bounded_retrieval_decision_receipt_trace",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRetrievalPlanV1,
		PayloadKind:        "adaptive_retrieval_plan",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRetrievalProgressV1,
		PayloadKind:        "retrieval_progress",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractReusableSkillCandidateV1,
		PayloadKind:        "inactive_verified_reusable_skill_candidate",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractReviewModeResponseV1,
		PayloadKind:        "review_mode_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRunAdvisorV1,
		PayloadKind:        "run_advisor",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRunnerCapabilityV1,
		PayloadKind:        "runner_capability",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRunnerQualitySampleV1,
		PayloadKind:        "runner_quality_sample",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRunnerResultV1,
		PayloadKind:        "runner_result",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRunnerSelectionV1,
		PayloadKind:        "advisor_only_runner_selection_receipt",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractScopedPolicyCardV1,
		PayloadKind:        "project_task_and_intent_scoped_retrieval_policy_card",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSkillDraftV1,
		PayloadKind:        "verified_workflow_skill_draft",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSkillEvaluationV1,
		PayloadKind:        "independent_skill_holdout_evaluation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSkillExportV1,
		PayloadKind:        "human_approved_inactive_skill_export",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSkillRetirementV1,
		PayloadKind:        "explicit_inactive_skill_draft_retirement",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSkillRetirementCandidateV1,
		PayloadKind:        "advisory_skill_retirement_candidate",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSteeringCommentV1,
		PayloadKind:        "steering_comment",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractStorageTemperatureDecisionV1,
		PayloadKind:        "utility_based_reversible_memory_storage_temperature_decision",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSynthesisPackV1,
		PayloadKind:        "synthesis_pack",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSynthesisPackV2,
		PayloadKind:        "proof_carrying_synthesis_pack",
		ContractVersion:    2,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractTaskIdentityReceiptV1,
		PayloadKind:        "task_identity_receipt",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractTaskIdentityReconciliationV1,
		PayloadKind:        "task_identity_reconciliation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractTemporalClaimV1,
		PayloadKind:        "temporal_claim",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractTemporalClaimQueryV1,
		PayloadKind:        "temporal_claim_query",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractUniversalAgentAdapterResponseV1,
		PayloadKind:        "universal_agent_adapter_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractUtilityAnalyticsV1,
		PayloadKind:        "entitled_continuous_utility_cohort_analytics",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractUtilityLedgerV1,
		PayloadKind:        "bounded_verified_utility_ledger",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractUtilityObservationV1,
		PayloadKind:        "verified_utility_observation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractUtilityPolicyEvaluationV1,
		PayloadKind:        "entitled_advisory_verified_utility_policy_gate",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractWritebackResultV1,
		PayloadKind:        "writeback_result",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
}
