// Code generated by scripts/agent/generate-agent-contract-types; DO NOT EDIT.

package main

type GeneratedAgentContractRef struct {
	SchemaID           string
	PayloadKind        string
	ContractVersion    int
	RequiredOutputMode string
}

const GeneratedAgentContractRegistryID = "contextlattice_agent_output_contracts"
const GeneratedAgentContractRegistryVersion = 27

const GeneratedAgentContractA2aReadinessProfileV1 = "a2a_readiness_profile.v1"
const GeneratedAgentContractAgentFlightRecorderEventV1 = "agent_flight_recorder_event.v1"
const GeneratedAgentContractAgentPacketV1 = "agent_packet.v1"
const GeneratedAgentContractAgentPacketDeltaV1 = "agent_packet_delta.v1"
const GeneratedAgentContractAgentPacketReconstructionV1 = "agent_packet_reconstruction.v1"
const GeneratedAgentContractAgentPreflightResponseV1 = "agent_preflight_response.v1"
const GeneratedAgentContractAgentPromptContextPackageV1 = "agent_prompt_context_package.v1"
const GeneratedAgentContractAgentRunTraceV1 = "agent_run_trace.v1"
const GeneratedAgentContractAgentSessionRollupV1 = "agent_session_rollup.v1"
const GeneratedAgentContractAgentSpanV1 = "agent_span.v1"
const GeneratedAgentContractAgentTaskLeaseV1 = "agent_task_lease.v1"
const GeneratedAgentContractAgentTaskResultV1 = "agent_task_result.v1"
const GeneratedAgentContractAntiSchemingProtocolV1 = "anti_scheming_protocol.v1"
const GeneratedAgentContractCodexCompactHookStdoutV1 = "codex_compact_hook_stdout.v1"
const GeneratedAgentContractContextMeshEnvelopeV1 = "context_mesh_envelope.v1"
const GeneratedAgentContractContextMeshGrantV1 = "context_mesh_grant.v1"
const GeneratedAgentContractContextMeshImportV1 = "context_mesh_import.v1"
const GeneratedAgentContractContextMeshRevocationV1 = "context_mesh_revocation.v1"
const GeneratedAgentContractContextOverflowRecoveryV1 = "context_overflow_recovery.v1"
const GeneratedAgentContractContextPackResponseV1 = "context_pack_response.v1"
const GeneratedAgentContractContextPassportV1 = "context_passport.v1"
const GeneratedAgentContractContextPassportDiffV1 = "context_passport_diff.v1"
const GeneratedAgentContractContextPassportReplayV1 = "context_passport_replay.v1"
const GeneratedAgentContractContextPassportVerifyV1 = "context_passport_verify.v1"
const GeneratedAgentContractContextPolicyCandidateV1 = "context_policy_candidate.v1"
const GeneratedAgentContractContextPolicyEvaluationV1 = "context_policy_evaluation.v1"
const GeneratedAgentContractContextlatticeLifecycleReceiptV1 = "contextlattice_lifecycle_receipt.v1"
const GeneratedAgentContractContractAcknowledgementV1 = "contract_acknowledgement.v1"
const GeneratedAgentContractDecisionChangeV1 = "decision_change.v1"
const GeneratedAgentContractDecisionChangeQueryV1 = "decision_change_query.v1"
const GeneratedAgentContractDreamModeResponseV1 = "dream_mode_response.v1"
const GeneratedAgentContractObjectiveGraphV1 = "objective_graph.v1"
const GeneratedAgentContractObjectiveRuntimeStateV1 = "objective_runtime_state.v1"
const GeneratedAgentContractObjectiveTransitionV1 = "objective_transition.v1"
const GeneratedAgentContractPolicyContextPackageV1 = "policy_context_package.v1"
const GeneratedAgentContractRetrievalPlanV1 = "retrieval_plan.v1"
const GeneratedAgentContractRetrievalProgressV1 = "retrieval_progress.v1"
const GeneratedAgentContractReviewModeResponseV1 = "review_mode_response.v1"
const GeneratedAgentContractRunAdvisorV1 = "run_advisor.v1"
const GeneratedAgentContractRunnerCapabilityV1 = "runner_capability.v1"
const GeneratedAgentContractRunnerQualitySampleV1 = "runner_quality_sample.v1"
const GeneratedAgentContractRunnerResultV1 = "runner_result.v1"
const GeneratedAgentContractSkillDraftV1 = "skill_draft.v1"
const GeneratedAgentContractSkillEvaluationV1 = "skill_evaluation.v1"
const GeneratedAgentContractSkillExportV1 = "skill_export.v1"
const GeneratedAgentContractSkillRetirementV1 = "skill_retirement.v1"
const GeneratedAgentContractSteeringCommentV1 = "steering_comment.v1"
const GeneratedAgentContractSynthesisPackV1 = "synthesis_pack.v1"
const GeneratedAgentContractSynthesisPackV2 = "synthesis_pack.v2"
const GeneratedAgentContractTaskIdentityReceiptV1 = "task_identity_receipt.v1"
const GeneratedAgentContractTaskIdentityReconciliationV1 = "task_identity_reconciliation.v1"
const GeneratedAgentContractTemporalClaimV1 = "temporal_claim.v1"
const GeneratedAgentContractTemporalClaimQueryV1 = "temporal_claim_query.v1"
const GeneratedAgentContractUniversalAgentAdapterResponseV1 = "universal_agent_adapter_response.v1"
const GeneratedAgentContractWritebackResultV1 = "writeback_result.v1"

var GeneratedAgentContractIDs = []string{
	GeneratedAgentContractA2aReadinessProfileV1,
	GeneratedAgentContractAgentFlightRecorderEventV1,
	GeneratedAgentContractAgentPacketV1,
	GeneratedAgentContractAgentPacketDeltaV1,
	GeneratedAgentContractAgentPacketReconstructionV1,
	GeneratedAgentContractAgentPreflightResponseV1,
	GeneratedAgentContractAgentPromptContextPackageV1,
	GeneratedAgentContractAgentRunTraceV1,
	GeneratedAgentContractAgentSessionRollupV1,
	GeneratedAgentContractAgentSpanV1,
	GeneratedAgentContractAgentTaskLeaseV1,
	GeneratedAgentContractAgentTaskResultV1,
	GeneratedAgentContractAntiSchemingProtocolV1,
	GeneratedAgentContractCodexCompactHookStdoutV1,
	GeneratedAgentContractContextMeshEnvelopeV1,
	GeneratedAgentContractContextMeshGrantV1,
	GeneratedAgentContractContextMeshImportV1,
	GeneratedAgentContractContextMeshRevocationV1,
	GeneratedAgentContractContextOverflowRecoveryV1,
	GeneratedAgentContractContextPackResponseV1,
	GeneratedAgentContractContextPassportV1,
	GeneratedAgentContractContextPassportDiffV1,
	GeneratedAgentContractContextPassportReplayV1,
	GeneratedAgentContractContextPassportVerifyV1,
	GeneratedAgentContractContextPolicyCandidateV1,
	GeneratedAgentContractContextPolicyEvaluationV1,
	GeneratedAgentContractContextlatticeLifecycleReceiptV1,
	GeneratedAgentContractContractAcknowledgementV1,
	GeneratedAgentContractDecisionChangeV1,
	GeneratedAgentContractDecisionChangeQueryV1,
	GeneratedAgentContractDreamModeResponseV1,
	GeneratedAgentContractObjectiveGraphV1,
	GeneratedAgentContractObjectiveRuntimeStateV1,
	GeneratedAgentContractObjectiveTransitionV1,
	GeneratedAgentContractPolicyContextPackageV1,
	GeneratedAgentContractRetrievalPlanV1,
	GeneratedAgentContractRetrievalProgressV1,
	GeneratedAgentContractReviewModeResponseV1,
	GeneratedAgentContractRunAdvisorV1,
	GeneratedAgentContractRunnerCapabilityV1,
	GeneratedAgentContractRunnerQualitySampleV1,
	GeneratedAgentContractRunnerResultV1,
	GeneratedAgentContractSkillDraftV1,
	GeneratedAgentContractSkillEvaluationV1,
	GeneratedAgentContractSkillExportV1,
	GeneratedAgentContractSkillRetirementV1,
	GeneratedAgentContractSteeringCommentV1,
	GeneratedAgentContractSynthesisPackV1,
	GeneratedAgentContractSynthesisPackV2,
	GeneratedAgentContractTaskIdentityReceiptV1,
	GeneratedAgentContractTaskIdentityReconciliationV1,
	GeneratedAgentContractTemporalClaimV1,
	GeneratedAgentContractTemporalClaimQueryV1,
	GeneratedAgentContractUniversalAgentAdapterResponseV1,
	GeneratedAgentContractWritebackResultV1,
}

var GeneratedAgentContracts = []GeneratedAgentContractRef{
	{
		SchemaID:           GeneratedAgentContractA2aReadinessProfileV1,
		PayloadKind:        "a2a_readiness_profile",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentFlightRecorderEventV1,
		PayloadKind:        "agent_flight_recorder_event",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPacketV1,
		PayloadKind:        "compact_prompt_ready_agent_packet",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPacketDeltaV1,
		PayloadKind:        "deterministic_agent_packet_delta",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPacketReconstructionV1,
		PayloadKind:        "verified_agent_packet_reconstruction",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPreflightResponseV1,
		PayloadKind:        "agent_preflight_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPromptContextPackageV1,
		PayloadKind:        "agent_prompt_context_package",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentRunTraceV1,
		PayloadKind:        "agent_run_trace",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentSessionRollupV1,
		PayloadKind:        "agent_session_rollup",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentSpanV1,
		PayloadKind:        "agent_span",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentTaskLeaseV1,
		PayloadKind:        "agent_task_lease",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentTaskResultV1,
		PayloadKind:        "agent_task_result",
		ContractVersion:    1,
		RequiredOutputMode: "json_object_or_markdown_with_json_frontmatter",
	},
	{
		SchemaID:           GeneratedAgentContractAntiSchemingProtocolV1,
		PayloadKind:        "policy_fragment",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractCodexCompactHookStdoutV1,
		PayloadKind:        "codex_compact_hook_stdout",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextMeshEnvelopeV1,
		PayloadKind:        "transport_neutral_encrypted_context_envelope",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextMeshGrantV1,
		PayloadKind:        "signed_project_scoped_mesh_grant",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextMeshImportV1,
		PayloadKind:        "verified_context_mesh_reconciliation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextMeshRevocationV1,
		PayloadKind:        "signed_local_mesh_revocation_tombstone",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextOverflowRecoveryV1,
		PayloadKind:        "context_overflow_recovery",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPackResponseV1,
		PayloadKind:        "context_pack_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPassportV1,
		PayloadKind:        "signed_replayable_context_passport",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPassportDiffV1,
		PayloadKind:        "context_passport_diff",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPassportReplayV1,
		PayloadKind:        "context_passport_replay_plan",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPassportVerifyV1,
		PayloadKind:        "context_passport_verification",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPolicyCandidateV1,
		PayloadKind:        "outcome_trained_context_policy_candidate",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPolicyEvaluationV1,
		PayloadKind:        "context_policy_canary_evaluation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextlatticeLifecycleReceiptV1,
		PayloadKind:        "contextlattice_lifecycle_receipt",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContractAcknowledgementV1,
		PayloadKind:        "contract_acknowledgement",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractDecisionChangeV1,
		PayloadKind:        "decision_change",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractDecisionChangeQueryV1,
		PayloadKind:        "decision_change_query",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractDreamModeResponseV1,
		PayloadKind:        "dream_mode_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractObjectiveGraphV1,
		PayloadKind:        "longitudinal_objective_graph",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractObjectiveRuntimeStateV1,
		PayloadKind:        "objective_runtime_state",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractObjectiveTransitionV1,
		PayloadKind:        "objective_transition",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractPolicyContextPackageV1,
		PayloadKind:        "agent_policy_context_package",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRetrievalPlanV1,
		PayloadKind:        "adaptive_retrieval_plan",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRetrievalProgressV1,
		PayloadKind:        "retrieval_progress",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractReviewModeResponseV1,
		PayloadKind:        "review_mode_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRunAdvisorV1,
		PayloadKind:        "run_advisor",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRunnerCapabilityV1,
		PayloadKind:        "runner_capability",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRunnerQualitySampleV1,
		PayloadKind:        "runner_quality_sample",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractRunnerResultV1,
		PayloadKind:        "runner_result",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSkillDraftV1,
		PayloadKind:        "verified_workflow_skill_draft",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSkillEvaluationV1,
		PayloadKind:        "independent_skill_holdout_evaluation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSkillExportV1,
		PayloadKind:        "human_approved_inactive_skill_export",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSkillRetirementV1,
		PayloadKind:        "explicit_inactive_skill_draft_retirement",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSteeringCommentV1,
		PayloadKind:        "steering_comment",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSynthesisPackV1,
		PayloadKind:        "synthesis_pack",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractSynthesisPackV2,
		PayloadKind:        "proof_carrying_synthesis_pack",
		ContractVersion:    2,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractTaskIdentityReceiptV1,
		PayloadKind:        "task_identity_receipt",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractTaskIdentityReconciliationV1,
		PayloadKind:        "task_identity_reconciliation",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractTemporalClaimV1,
		PayloadKind:        "temporal_claim",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractTemporalClaimQueryV1,
		PayloadKind:        "temporal_claim_query",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractUniversalAgentAdapterResponseV1,
		PayloadKind:        "universal_agent_adapter_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractWritebackResultV1,
		PayloadKind:        "writeback_result",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
}
