// Code generated by scripts/agent/generate-agent-contract-types; DO NOT EDIT.

package main

type GeneratedAgentContractRef struct {
	SchemaID           string
	PayloadKind        string
	ContractVersion    int
	RequiredOutputMode string
}

const GeneratedAgentContractRegistryID = "contextlattice_agent_output_contracts"
const GeneratedAgentContractRegistryVersion = 6

const GeneratedAgentContractA2aReadinessProfileV1 = "a2a_readiness_profile.v1"
const GeneratedAgentContractAgentFlightRecorderEventV1 = "agent_flight_recorder_event.v1"
const GeneratedAgentContractAgentPreflightResponseV1 = "agent_preflight_response.v1"
const GeneratedAgentContractAgentPromptContextPackageV1 = "agent_prompt_context_package.v1"
const GeneratedAgentContractAgentRunTraceV1 = "agent_run_trace.v1"
const GeneratedAgentContractAgentSessionRollupV1 = "agent_session_rollup.v1"
const GeneratedAgentContractAgentSpanV1 = "agent_span.v1"
const GeneratedAgentContractAgentTaskResultV1 = "agent_task_result.v1"
const GeneratedAgentContractAntiSchemingProtocolV1 = "anti_scheming_protocol.v1"
const GeneratedAgentContractCodexCompactHookStdoutV1 = "codex_compact_hook_stdout.v1"
const GeneratedAgentContractContextOverflowRecoveryV1 = "context_overflow_recovery.v1"
const GeneratedAgentContractContextPackResponseV1 = "context_pack_response.v1"
const GeneratedAgentContractContractAcknowledgementV1 = "contract_acknowledgement.v1"
const GeneratedAgentContractDreamModeResponseV1 = "dream_mode_response.v1"
const GeneratedAgentContractObjectiveRuntimeStateV1 = "objective_runtime_state.v1"
const GeneratedAgentContractPolicyContextPackageV1 = "policy_context_package.v1"
const GeneratedAgentContractUniversalAgentAdapterResponseV1 = "universal_agent_adapter_response.v1"
const GeneratedAgentContractWritebackResultV1 = "writeback_result.v1"

var GeneratedAgentContractIDs = []string{
	GeneratedAgentContractA2aReadinessProfileV1,
	GeneratedAgentContractAgentFlightRecorderEventV1,
	GeneratedAgentContractAgentPreflightResponseV1,
	GeneratedAgentContractAgentPromptContextPackageV1,
	GeneratedAgentContractAgentRunTraceV1,
	GeneratedAgentContractAgentSessionRollupV1,
	GeneratedAgentContractAgentSpanV1,
	GeneratedAgentContractAgentTaskResultV1,
	GeneratedAgentContractAntiSchemingProtocolV1,
	GeneratedAgentContractCodexCompactHookStdoutV1,
	GeneratedAgentContractContextOverflowRecoveryV1,
	GeneratedAgentContractContextPackResponseV1,
	GeneratedAgentContractContractAcknowledgementV1,
	GeneratedAgentContractDreamModeResponseV1,
	GeneratedAgentContractObjectiveRuntimeStateV1,
	GeneratedAgentContractPolicyContextPackageV1,
	GeneratedAgentContractUniversalAgentAdapterResponseV1,
	GeneratedAgentContractWritebackResultV1,
}

var GeneratedAgentContracts = []GeneratedAgentContractRef{
	{
		SchemaID:           GeneratedAgentContractA2aReadinessProfileV1,
		PayloadKind:        "a2a_readiness_profile",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentFlightRecorderEventV1,
		PayloadKind:        "agent_flight_recorder_event",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPreflightResponseV1,
		PayloadKind:        "agent_preflight_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentPromptContextPackageV1,
		PayloadKind:        "agent_prompt_context_package",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentRunTraceV1,
		PayloadKind:        "agent_run_trace",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentSessionRollupV1,
		PayloadKind:        "agent_session_rollup",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentSpanV1,
		PayloadKind:        "agent_span",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractAgentTaskResultV1,
		PayloadKind:        "agent_task_result",
		ContractVersion:    1,
		RequiredOutputMode: "json_object_or_markdown_with_json_frontmatter",
	},
	{
		SchemaID:           GeneratedAgentContractAntiSchemingProtocolV1,
		PayloadKind:        "policy_fragment",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractCodexCompactHookStdoutV1,
		PayloadKind:        "codex_compact_hook_stdout",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextOverflowRecoveryV1,
		PayloadKind:        "context_overflow_recovery",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContextPackResponseV1,
		PayloadKind:        "context_pack_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractContractAcknowledgementV1,
		PayloadKind:        "contract_acknowledgement",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractDreamModeResponseV1,
		PayloadKind:        "dream_mode_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractObjectiveRuntimeStateV1,
		PayloadKind:        "objective_runtime_state",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractPolicyContextPackageV1,
		PayloadKind:        "agent_policy_context_package",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractUniversalAgentAdapterResponseV1,
		PayloadKind:        "universal_agent_adapter_response",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
	{
		SchemaID:           GeneratedAgentContractWritebackResultV1,
		PayloadKind:        "writeback_result",
		ContractVersion:    1,
		RequiredOutputMode: "json_object",
	},
}
