// Code generated by scripts/generate_commercial_truth.py; DO NOT EDIT.

package main

import (
	"regexp"
	"strings"
)

const commercialTruthSchemaID = "contextlattice_commercial_truth.v1"
const commercialTruthProductVersion = "4.0.6"
const commercialTruthStableTag = "v4.0.6"
const commercialTruthReleaseTrain = "4.0"
const commercialTruthContractSHA256 = "61b14b27f249580771e6733ae95c11499410c39fb46986e5bb5b57f99f93fd80"

type commercialTruthLimits struct {
	MaxAPIKeys    *int
	MaxProjects   *int
	MaxWriteBytes *int
	IncludedSeats *int
}

type commercialTruthPlan struct {
	ID                   string
	BuyerLabel           string
	Description          string
	Paid                 bool
	SelfServePurchasable bool
	MonthlyUSD           *int
	AnnualUSD            *int
	CustomPricing        bool
	Limits               commercialTruthLimits
	FeatureIDs           []string
}

type commercialTruthAliasPattern struct {
	Pattern *regexp.Regexp
	Target  string
}

type commercialTruthFeatureRouteRequirement struct {
	FeatureID       string
	EligiblePlanIDs []string
	AllowedRoles    []string
}

func commercialTruthInt(value int) *int { return &value }

var commercialTruthPlans = map[string]commercialTruthPlan{
	"free":       {ID: "free", BuyerLabel: "Free", Description: "Local-first core for individual builders and evaluation.", Paid: false, SelfServePurchasable: false, MonthlyUSD: commercialTruthInt(0), AnnualUSD: commercialTruthInt(0), CustomPricing: false, Limits: commercialTruthLimits{MaxAPIKeys: nil, MaxProjects: nil, MaxWriteBytes: nil, IncludedSeats: commercialTruthInt(1)}, FeatureIDs: []string{"cli_workflows", "local_go_rust_runtime", "durable_memory", "staged_retrieval", "agent_session_context", "dashboard_visibility", "frontier_verified_utility_ledger", "frontier_aggregate_signal"}},
	"starter":    {ID: "starter", BuyerLabel: "Starter", Description: "Paid single-operator access to hosted artifacts and protected runtime operations.", Paid: true, SelfServePurchasable: true, MonthlyUSD: commercialTruthInt(24), AnnualUSD: commercialTruthInt(240), CustomPricing: false, Limits: commercialTruthLimits{MaxAPIKeys: commercialTruthInt(3), MaxProjects: commercialTruthInt(5), MaxWriteBytes: commercialTruthInt(50000), IncludedSeats: commercialTruthInt(1)}, FeatureIDs: []string{"cli_workflows", "local_go_rust_runtime", "durable_memory", "staged_retrieval", "agent_session_context", "dashboard_visibility", "premium_artifact_downloads", "premium_runtime_keys", "protected_runtime_operations", "frontier_verified_utility_ledger", "frontier_utility_analytics", "frontier_continuity_zero_automation", "frontier_aggregate_signal"}},
	"team":       {ID: "team", BuyerLabel: "Team", Description: "Shared workspace and analytics access for teams shipping agent workflows.", Paid: true, SelfServePurchasable: true, MonthlyUSD: commercialTruthInt(99), AnnualUSD: commercialTruthInt(990), CustomPricing: false, Limits: commercialTruthLimits{MaxAPIKeys: commercialTruthInt(10), MaxProjects: commercialTruthInt(25), MaxWriteBytes: commercialTruthInt(200000), IncludedSeats: commercialTruthInt(5)}, FeatureIDs: []string{"cli_workflows", "local_go_rust_runtime", "durable_memory", "staged_retrieval", "agent_session_context", "dashboard_visibility", "premium_artifact_downloads", "premium_runtime_keys", "shared_workspace_controls", "pro_analytics", "protected_runtime_operations", "frontier_semantic_continuity_automation", "frontier_shared_objective_graph", "frontier_shared_decision_provenance", "frontier_verified_utility_ledger", "frontier_utility_analytics", "frontier_retrieval_receipt_governance", "frontier_causal_bridge_governance", "frontier_continuity_zero_automation", "frontier_aggregate_signal"}},
	"operator":   {ID: "operator", BuyerLabel: "Operator", Description: "Advanced operator lane for protected runtime operations and analytics.", Paid: true, SelfServePurchasable: true, MonthlyUSD: commercialTruthInt(299), AnnualUSD: commercialTruthInt(2990), CustomPricing: false, Limits: commercialTruthLimits{MaxAPIKeys: nil, MaxProjects: nil, MaxWriteBytes: nil, IncludedSeats: commercialTruthInt(1)}, FeatureIDs: []string{"cli_workflows", "local_go_rust_runtime", "durable_memory", "staged_retrieval", "agent_session_context", "dashboard_visibility", "premium_artifact_downloads", "premium_runtime_keys", "pro_analytics", "protected_runtime_operations", "frontier_semantic_continuity_automation", "frontier_shared_objective_graph", "frontier_verified_utility_ledger", "frontier_utility_analytics", "frontier_verified_efficiency_operations", "frontier_retrieval_receipt_governance", "frontier_causal_bridge_governance", "frontier_continuous_counterfactual_eval", "frontier_evidence_reputation_activation", "frontier_continuous_retrieval_regression", "frontier_adversarial_defense_operations", "frontier_policy_laboratory_automation", "frontier_agent_fit_governance", "frontier_portable_continuation_governance", "frontier_skill_evolution_governance", "frontier_continuity_zero_automation", "frontier_aggregate_signal", "frontier_private_aggregate_learning"}},
	"enterprise": {ID: "enterprise", BuyerLabel: "Enterprise", Description: "Custom-priced enterprise access with workspace controls and SCIM token management.", Paid: true, SelfServePurchasable: false, MonthlyUSD: nil, AnnualUSD: nil, CustomPricing: true, Limits: commercialTruthLimits{MaxAPIKeys: commercialTruthInt(100), MaxProjects: nil, MaxWriteBytes: nil, IncludedSeats: commercialTruthInt(100)}, FeatureIDs: []string{"cli_workflows", "local_go_rust_runtime", "durable_memory", "staged_retrieval", "agent_session_context", "dashboard_visibility", "premium_artifact_downloads", "premium_runtime_keys", "shared_workspace_controls", "pro_analytics", "protected_runtime_operations", "frontier_semantic_continuity_automation", "frontier_shared_objective_graph", "frontier_shared_decision_provenance", "frontier_verified_utility_ledger", "frontier_utility_analytics", "frontier_verified_efficiency_operations", "scim_token_management", "frontier_retrieval_receipt_governance", "frontier_causal_bridge_governance", "frontier_continuous_counterfactual_eval", "frontier_evidence_reputation_activation", "frontier_continuous_retrieval_regression", "frontier_adversarial_defense_operations", "frontier_policy_laboratory_automation", "frontier_agent_fit_governance", "frontier_portable_continuation_governance", "frontier_skill_evolution_governance", "frontier_continuity_zero_automation", "frontier_aggregate_signal", "frontier_private_aggregate_learning"}},
}

var commercialTruthPlanAliases = map[string]string{
	"pro":      "operator",
	"business": "team",
}

var commercialTruthPlanAliasPatterns = []commercialTruthAliasPattern{
	{Pattern: regexp.MustCompile("^enterprise-seats-[0-9]+$"), Target: "enterprise"},
}

var commercialTruthProtectedPaidRoutes = []string{
	"/v1/inference/route",
	"/v1/inference/chat",
	"/v1/inference/runtime-policy",
	"/v1/inference/embedding-policy",
	"/maintenance/storage/run",
	"/maintenance/memory/graph/prune-volatile",
	"/maintenance/telemetry/blob-gc",
	"/migration/runtime",
	"/memory/context-policy/activate",
	"/memory/context-policy/deactivate",
	"/memory/skills/foundry/activate",
	"/memory/skills/foundry/deactivate",
	"/memory/context-mesh/orchestrate",
	"/memory/continuity/automation",
	"/memory/objectives/shared",
	"/memory/decision-changes/shared",
	"/telemetry/utility/analytics",
	"/telemetry/utility/policy/evaluate",
	"/memory/retrieval/receipts/governance",
	"/memory/causal-bridges/governance",
	"/memory/retrieval/ablation/operations",
	"/memory/evidence-reputation/activation",
	"/memory/recall/regressions/operations",
	"/memory/trust/defense/operations",
	"/memory/policy/simulation/history",
	"/memory/policy/scoped/activation",
	"/memory/context-policy/canary",
	"/memory/lifecycle/automation",
	"/memory/contradictions/review-queue",
	"/memory/storage/temperature/automation",
	"/memory/agent-fit/steering/governance",
	"/memory/agent-fit/profile/governance",
	"/memory/agent-fit/context-prep/governance",
	"/memory/agent-fit/selection/activation",
	"/memory/portable-continuation/governance",
	"/memory/skills/foundry/evolution/governance",
	"/memory/continuity-zero/governance",
	"/memory/aggregate-signal/governance",
}

var commercialTruthPaidRouteEligiblePlans = []string{"starter", "team", "operator", "enterprise"}
var commercialTruthPaidRouteAllowedRoles = []string{"owner", "admin"}

var commercialTruthPaidFeatureRouteRequirements = map[string]commercialTruthFeatureRouteRequirement{
	"/memory/continuity/automation":               {FeatureID: "frontier_semantic_continuity_automation", EligiblePlanIDs: []string{"team", "operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/objectives/shared":                   {FeatureID: "frontier_shared_objective_graph", EligiblePlanIDs: []string{"team", "operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/decision-changes/shared":             {FeatureID: "frontier_shared_decision_provenance", EligiblePlanIDs: []string{"team", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/telemetry/utility/analytics":                {FeatureID: "frontier_utility_analytics", EligiblePlanIDs: []string{"starter", "team", "operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/telemetry/utility/policy/evaluate":          {FeatureID: "frontier_verified_efficiency_operations", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/retrieval/receipts/governance":       {FeatureID: "frontier_retrieval_receipt_governance", EligiblePlanIDs: []string{"team", "operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/causal-bridges/governance":           {FeatureID: "frontier_causal_bridge_governance", EligiblePlanIDs: []string{"team", "operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/retrieval/ablation/operations":       {FeatureID: "frontier_continuous_counterfactual_eval", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/evidence-reputation/activation":      {FeatureID: "frontier_evidence_reputation_activation", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/recall/regressions/operations":       {FeatureID: "frontier_continuous_retrieval_regression", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/trust/defense/operations":            {FeatureID: "frontier_adversarial_defense_operations", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/policy/simulation/history":           {FeatureID: "frontier_policy_laboratory_automation", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/policy/scoped/activation":            {FeatureID: "frontier_policy_laboratory_automation", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/context-policy/canary":               {FeatureID: "frontier_policy_laboratory_automation", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/lifecycle/automation":                {FeatureID: "frontier_policy_laboratory_automation", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/contradictions/review-queue":         {FeatureID: "frontier_policy_laboratory_automation", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/storage/temperature/automation":      {FeatureID: "frontier_policy_laboratory_automation", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/agent-fit/steering/governance":       {FeatureID: "frontier_agent_fit_governance", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/agent-fit/profile/governance":        {FeatureID: "frontier_agent_fit_governance", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/agent-fit/context-prep/governance":   {FeatureID: "frontier_agent_fit_governance", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/agent-fit/selection/activation":      {FeatureID: "frontier_agent_fit_governance", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/portable-continuation/governance":    {FeatureID: "frontier_portable_continuation_governance", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/skills/foundry/evolution/governance": {FeatureID: "frontier_skill_evolution_governance", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/continuity-zero/governance":          {FeatureID: "frontier_continuity_zero_automation", EligiblePlanIDs: []string{"starter", "team", "operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
	"/memory/aggregate-signal/governance":         {FeatureID: "frontier_private_aggregate_learning", EligiblePlanIDs: []string{"operator", "enterprise"}, AllowedRoles: []string{"owner", "admin"}},
}

func commercialTruthPaidRouteRequiredFeature(path string) string {
	return commercialTruthPaidFeatureRouteRequirements[strings.TrimSpace(path)].FeatureID
}

func normalizeCommercialTruthPlanID(raw string) string {
	plan := strings.ToLower(strings.TrimSpace(raw))
	if plan == "" {
		return ""
	}
	if _, ok := commercialTruthPlans[plan]; ok {
		return plan
	}
	if target, ok := commercialTruthPlanAliases[plan]; ok {
		return target
	}
	for _, alias := range commercialTruthPlanAliasPatterns {
		if alias.Pattern.MatchString(plan) {
			return alias.Target
		}
	}
	return ""
}
