// Code generated by scripts/generate_commercial_truth.py; DO NOT EDIT.

package main

import (
	"regexp"
	"strings"
)

const commercialTruthSchemaID = "contextlattice_commercial_truth.v1"
const commercialTruthProductVersion = "3.17.5"
const commercialTruthStableTag = "v3.17.5"
const commercialTruthReleaseTrain = "3.17"
const commercialTruthContractSHA256 = "91ab3180fa8800f17762bc826eab4f0e38f5176a1868caf5c8e473030c8dfe60"

type commercialTruthLimits struct {
	MaxAPIKeys    *int
	MaxProjects   *int
	MaxWriteBytes *int
	IncludedSeats *int
}

type commercialTruthPlan struct {
	ID                   string
	BuyerLabel           string
	Description          string
	Paid                 bool
	SelfServePurchasable bool
	MonthlyUSD           *int
	AnnualUSD            *int
	CustomPricing        bool
	Limits               commercialTruthLimits
	FeatureIDs           []string
}

type commercialTruthAliasPattern struct {
	Pattern *regexp.Regexp
	Target  string
}

func commercialTruthInt(value int) *int { return &value }

var commercialTruthPlans = map[string]commercialTruthPlan{
	"free":       {ID: "free", BuyerLabel: "Free", Description: "Local-first core for individual builders and evaluation.", Paid: false, SelfServePurchasable: false, MonthlyUSD: commercialTruthInt(0), AnnualUSD: commercialTruthInt(0), CustomPricing: false, Limits: commercialTruthLimits{MaxAPIKeys: nil, MaxProjects: nil, MaxWriteBytes: nil, IncludedSeats: nil}, FeatureIDs: []string{"cli_workflows", "local_go_rust_runtime", "durable_memory", "staged_retrieval", "agent_session_context", "dashboard_visibility"}},
	"starter":    {ID: "starter", BuyerLabel: "Starter", Description: "Paid single-operator access to hosted artifacts and protected runtime operations.", Paid: true, SelfServePurchasable: true, MonthlyUSD: commercialTruthInt(24), AnnualUSD: commercialTruthInt(240), CustomPricing: false, Limits: commercialTruthLimits{MaxAPIKeys: commercialTruthInt(3), MaxProjects: commercialTruthInt(5), MaxWriteBytes: commercialTruthInt(50000), IncludedSeats: nil}, FeatureIDs: []string{"cli_workflows", "local_go_rust_runtime", "durable_memory", "staged_retrieval", "agent_session_context", "dashboard_visibility", "premium_artifact_downloads", "premium_runtime_keys", "protected_runtime_operations"}},
	"team":       {ID: "team", BuyerLabel: "Team", Description: "Shared workspace and analytics access for teams shipping agent workflows.", Paid: true, SelfServePurchasable: true, MonthlyUSD: commercialTruthInt(99), AnnualUSD: commercialTruthInt(990), CustomPricing: false, Limits: commercialTruthLimits{MaxAPIKeys: commercialTruthInt(10), MaxProjects: commercialTruthInt(25), MaxWriteBytes: commercialTruthInt(200000), IncludedSeats: nil}, FeatureIDs: []string{"cli_workflows", "local_go_rust_runtime", "durable_memory", "staged_retrieval", "agent_session_context", "dashboard_visibility", "premium_artifact_downloads", "premium_runtime_keys", "shared_workspace_controls", "pro_analytics", "protected_runtime_operations"}},
	"operator":   {ID: "operator", BuyerLabel: "Operator", Description: "Advanced operator lane for protected runtime operations and analytics.", Paid: true, SelfServePurchasable: true, MonthlyUSD: commercialTruthInt(299), AnnualUSD: commercialTruthInt(2990), CustomPricing: false, Limits: commercialTruthLimits{MaxAPIKeys: nil, MaxProjects: nil, MaxWriteBytes: nil, IncludedSeats: nil}, FeatureIDs: []string{"cli_workflows", "local_go_rust_runtime", "durable_memory", "staged_retrieval", "agent_session_context", "dashboard_visibility", "premium_artifact_downloads", "premium_runtime_keys", "pro_analytics", "protected_runtime_operations"}},
	"enterprise": {ID: "enterprise", BuyerLabel: "Enterprise", Description: "Custom-priced enterprise access with existing workspace and provisioning controls.", Paid: true, SelfServePurchasable: false, MonthlyUSD: nil, AnnualUSD: nil, CustomPricing: true, Limits: commercialTruthLimits{MaxAPIKeys: commercialTruthInt(100), MaxProjects: nil, MaxWriteBytes: nil, IncludedSeats: commercialTruthInt(100)}, FeatureIDs: []string{"cli_workflows", "local_go_rust_runtime", "durable_memory", "staged_retrieval", "agent_session_context", "dashboard_visibility", "premium_artifact_downloads", "premium_runtime_keys", "shared_workspace_controls", "pro_analytics", "protected_runtime_operations", "scim_token_management"}},
}

var commercialTruthPlanAliases = map[string]string{
	"pro":      "operator",
	"business": "team",
}

var commercialTruthPlanAliasPatterns = []commercialTruthAliasPattern{
	{Pattern: regexp.MustCompile("^enterprise-seats-[0-9]+$"), Target: "enterprise"},
}

var commercialTruthProtectedPaidRoutes = []string{
	"/v1/inference/route",
	"/v1/inference/chat",
	"/v1/inference/runtime-policy",
	"/v1/inference/embedding-policy",
	"/maintenance/storage/run",
	"/maintenance/memory/graph/prune-volatile",
	"/maintenance/telemetry/blob-gc",
	"/migration/runtime",
	"/memory/context-policy/activate",
	"/memory/context-policy/deactivate",
	"/memory/skills/foundry/activate",
	"/memory/skills/foundry/deactivate",
	"/memory/context-mesh/orchestrate",
}

var commercialTruthPaidRouteEligiblePlans = []string{"starter", "team", "operator", "enterprise"}
var commercialTruthPaidRouteAllowedRoles = []string{"owner", "admin"}

func normalizeCommercialTruthPlanID(raw string) string {
	plan := strings.ToLower(strings.TrimSpace(raw))
	if plan == "" {
		return ""
	}
	if _, ok := commercialTruthPlans[plan]; ok {
		return plan
	}
	if target, ok := commercialTruthPlanAliases[plan]; ok {
		return target
	}
	for _, alias := range commercialTruthPlanAliasPatterns {
		if alias.Pattern.MatchString(plan) {
			return alias.Target
		}
	}
	return ""
}
